### PR TITLE
Add post on activating SAP security audit log: INFODEV-2757

### PR DESCRIPTION
**Pull request by RackerKate**

### CODE REVIEW

**Comment by rackernexus** [comment]
HULK [PREVIEW](https://staging.developer.rackspace.com/build-d07e011144/)

**Comment by rackernexus** [comment]
If you want to double-check your formatting, check [the preview](https://staging.developer.rackspace.com/build-c18d271c4a/).

**Comment by rackernexus** [comment]
Your content preview [is now ready](https://staging.developer.rackspace.com/build-c18d271c4a/). :bow:

**Comment by rackernexus** [comment]
HULK [PREVIEW](https://staging.developer.rackspace.com/build-33f2c2d674/)

**Comment by rackernexus** [comment]
HULK [PREVIEW](https://staging.developer.rackspace.com/build-33f2c2d674/)

**Comment by rackernexus** [comment]
If you want to double-check your formatting, check [the preview](https://staging.developer.rackspace.com/build-920f80f850/).

**Comment by rackernexus** [comment]
:eyes: [Preview](https://staging.developer.rackspace.com/build-920f80f850/)

**Comment by rackernexus** [comment]
If you want to double-check your formatting, check [the preview](https://staging.developer.rackspace.com/build-e6cf7b0bdb/).

**Comment by rackernexus** [comment]
HULK [PREVIEW](https://staging.developer.rackspace.com/build-16fa2e3491/)

**Comment by rackernexus** [comment]
Your content preview [is now ready](https://staging.developer.rackspace.com/build-9c11bf52e3/). :bow:

**Comment by rackernexus** [comment]
Your content preview [is now ready](https://staging.developer.rackspace.com/build-4dc592699b/). :bow:

**Comment by rackernexus** [comment]
:mag_right: [Preview](https://staging.developer.rackspace.com/build-7b6b683def/)

**Comment by cyrichardson** [comment]
Gotcha. On it, @RackerKate.

**Comment by cyrichardson** [comment]
@RackerKate Some suggestions here: 
[blog_Activating-the-SAP-Security-Audit-Log-feature_cyrEdits.docx](https://github.com/rackerlabs/docs-developer-blog/files/2531396/blog_Activating-the-SAP-Security-Audit-Log-feature_cyrEdits.docx)

**Comment by rackernexus** [comment]
:eyes: [Preview](https://staging.developer.rackspace.com/build-8e8a01f8c9/)

**Comment by rackernexus** [comment]
Your content preview [is now ready](https://staging.developer.rackspace.com/build-8e8a01f8c9/). :bow:

**Comment by RackerKate** [comment]
@cyrichardson Please review.

**Comment by rackernexus** [comment]
:eyes: [Preview](https://staging.developer.rackspace.com/build-df81a72c33/)

**Comment by rackernexus** [comment]
If you want to double-check your formatting, check [the preview](https://staging.developer.rackspace.com/build-1c25dc847b/).

**Comment by RackerKate** [comment]
@stephamon Please review.

**Comment by stephamon** [comment]
Hey @RackerKate looks good to me, but I would suggest adding this link in a Resources section at the end of the article: https://help.sap.com/saphelp_nw70/helpdata/en/c7/69bcb7f36611d3a6510000e835363f/frameset.htm

Some of the opening paragraph is directly lifted from there.

**Comment by rackernexus** [comment]
HULK [PREVIEW](https://staging.developer.rackspace.com/build-f80818bec2/)

**Comment by RackerKate** [comment]
@catlook Ready for your review.

**Pull request merged**
