### PR TITLE
Kubertetris

### PR DESCRIPTION
**Pull request by jmbrinkman**
2019-10-29
Redaction: Yes
Comments: Yes

@catlook Please review.

### CODE REVIEW

**Comment by rackernexus** [comment]
Build 294 was successful. Staging content [Preview!](https://developer-revs.staging.deconst.org/build-44fe710bf/). valid for 14 days

**Comment by robb-romans** [comment]
Please do not commit `.DS_Store` files. Thanks.

**Comment by rackernexus** [comment]
Build 297 was successful. Staging content [Preview!](https://developer-revs.staging.deconst.org/build-9d2454179/). valid for 14 days

**Comment by jmbrinkman** [comment]
fixed error with an older post. ds_store files are deletes, must have pulled them in while pulling from the remote master previously

**Comment by jmbrinkman** [comment]
DS_store file was added here:

https://github.com/rackerlabs/docs-developer-blog/commit/17ba7c8dc46877d736684fc8891b0809fb3fe06a#diff-203b256b88a49368973e8f648d58da97

My editor autoremoves these files, hence the delete.

**Pull request merged**
