### PR TITLE
Add post on Oracle Virtual Directory: INFODEV-2025

### PR DESCRIPTION
**Pull request by RackerKate**

### CODE REVIEW

**Comment by rackernexus** [comment]
HULK [PREVIEW](https://staging.developer.rackspace.com/build-f80d6c3fd9/)

**Comment by rackernexus** [comment]
:mag_right: [Preview](https://staging.developer.rackspace.com/build-f80d6c3fd9/)

**Comment by rackernexus** [comment]
:mag_right: [Preview](https://staging.developer.rackspace.com/build-4b5d881847/)

**Comment by RackerKate** [comment]
@cyrichardson For your review please.

**Comment by cyrichardson** [comment]
@RackerKate, suggested changes here: 
[blog_Oracle-Virtual-Directory-A view-of-LDAP-solutions_cyrEdits.docx](https://github.com/rackerlabs/docs-developer-blog/files/2329643/blog_Oracle-Virtual-Directory-A.view-of-LDAP-solutions_cyrEdits.docx)

**Comment by rackernexus** [comment]
:mag_right: [Preview](https://staging.developer.rackspace.com/build-07e1d8cc59/)

**Comment by rackernexus** [comment]
:eyes: [Preview](https://staging.developer.rackspace.com/build-649afab59a/)

**Comment by RackerKate** [comment]
@catlook Please review/merge.

**Pull request merged**
