### PR TITLE
Added multiple blogs for Jonathon Hurley, Racker.  Here is his info:

### PR DESCRIPTION
**Pull request by catlook**
author(s) mini bio, soft capped to 75 words: "Other duties as assigned" best describes the road so far which includes architecture design and support for E-Commerce and Content organizations across the industry before joining Rackspace and becoming involved with the Digital Team to focus on practice areas for AEM, hybris, and similar software platforms.
author(s) social media contact info: n/a
accept or decline to allow redaction, editing or structure changes by technical writer staff: accept
desired date of publishing:  2015-11-07
whether or not you're willing to answer comments about your post (if you are, be sure to subscribe to your post comments by clicking on the Subscribe link at the very bottom of the post once it's published): always happy to discuss

### CODE REVIEW

**Comment by everett-toews** [comment]
What's the plan/schedule for publishing these?

We don't want to dump 6 posts onto the blog at once.

**Comment by catlook** [comment]
Jonathon,

Do you have specific public dates in mind?  I'd recommend doing one ever other day or so?

Everett,

What timing do you think is best?

-- Cat Lookabaugh, Sr. Information Developer
Rackspace Hosting - the #1 Managed Cloud Company
DevDocs on Developer Experience Team
Office: (210) 312-8193   Cell: (210) 364-1060
cat.lookabaugh@rackspace.com

We should not write so that it is possible for the reader to understand us, but so that it is impossible for him to misunderstand us. - Quintilian, rhetorician (c. 35-100)

Harmony + Learner + Responsibility + Context + Intellection + Arranger + Consistency + Relator + Input + Analytical

**Comment by catlook** [comment]
Hello Cat,


I'd be fine with whatever you think is best; I write these when inspiration strikes so I can't say when the next might be.


Jonathan Hurley
Enterprise Support Architect
Rackspace Digital Services
Office: 210-312-1497
Cell:   210-416-0701
(US) 800-480-0865 (UK) 0800-032-1667

________________________________

**Comment by everett-toews** [comment]
This has been split into 6 different PRs.

**Pull request closed without merging**
