### PR TITLE
add ebr blog and image folder

### PR DESCRIPTION
**Pull request by stephamon**
Add blog about EBR

### CODE REVIEW

**Comment by stephamon** [comment]
Hey @cyrichardson can you take a look at this please?

**Comment by rackernexus** [comment]
:mag_right: [Preview](https://staging.developer.rackspace.com/build-fd8c24f9eb/)

**Comment by cyrichardson** [comment]
Will do, @stephamon.

**Comment by cyrichardson** [comment]
@stephamon Suggested changes here: 
[Edition Based Redefinition (EBR) and enabling an application to support EBR_cyrEdits.docx](https://github.com/rackerlabs/docs-developer-blog/files/2193366/Edition.Based.Redefinition.EBR.and.enabling.an.application.to.support.EBR_cyrEdits.docx)

**Comment by rackernexus** [comment]
If you want to double-check your formatting, check [the preview](https://staging.developer.rackspace.com/build-d3b1f0e0c0/).

**Comment by rackernexus** [comment]
HULK [PREVIEW](https://staging.developer.rackspace.com/build-02f0604753/)

**Comment by rackernexus** [comment]
If you want to double-check your formatting, check [the preview](https://staging.developer.rackspace.com/build-3232def6a3/).

**Comment by rackernexus** [comment]
Your content preview [is now ready](https://staging.developer.rackspace.com/build-ecdc822c98/). :bow:

**Comment by rackernexus** [comment]
If you want to double-check your formatting, check [the preview](https://staging.developer.rackspace.com/build-158d1b014e/).

**Comment by rackernexus** [comment]
HULK [PREVIEW](https://staging.developer.rackspace.com/build-0b39e563d5/)

**Comment by rackernexus** [comment]
:mag_right: [Preview](https://staging.developer.rackspace.com/build-0b39e563d5/)

**Comment by rackernexus** [comment]
If you want to double-check your formatting, check [the preview](https://staging.developer.rackspace.com/build-afa4e3a66f/).

**Comment by rackernexus** [comment]
Your content preview [is now ready](https://staging.developer.rackspace.com/build-0008347895/). :bow:

**Comment by rackernexus** [comment]
:mag_right: [Preview](https://staging.developer.rackspace.com/build-ea55d6e7b8/)

**Pull request merged**
