### PR TITLE
Editorial changes

### PR DESCRIPTION
**Pull request by cyrichardson**

### CODE REVIEW

**Comment by cyrichardson** [comment]
@catlook Please review these changes and see if you agree with them and merge them if you do. Thanks!

**Comment by catlook** [comment]
build me

**Comment by rackernexus** [comment]
Build 1130 was successful. Staging content [Preview!](https://developer-revs.staging.deconst.org/build-467361c33/). valid for 14 days

**Comment by catlook** [comment]
build me

**Comment by rackernexus** [comment]
Build 1131 was successful. Staging content [Preview!](https://developer-revs.staging.deconst.org/build-467361c33/). valid for 14 days

**Comment by catlook** [comment]
build me

**Comment by rackernexus** [comment]
Build 1132 was successful. Staging content [Preview!](https://developer-revs.staging.deconst.org/build-071e13cf7/). valid for 14 days

**Comment by catlook** [comment]
build me

**Comment by catlook** [comment]
build me

**Comment by rackernexus** [comment]
Build 1134 was successful. Staging content [Preview!](https://developer-revs.staging.deconst.org/build-4c2d90e50/). valid for 14 days

**Pull request merged**
