### PR TITLE
RADDM

### PR DESCRIPTION
**Pull request by catlook**
In a comment on the pull request, include the following information and check off the list.

 - [ ] Mini bio
  - Soft capped to 75 words
 - [ ] Desired date of publishing
  - Make sure this matches the `date` in the front matter
 - [ ] Social media contact info
 - [ ] Redaction: (yes|no)
  - Allow redaction, editing or structure changes by technical writer staff
 - [ ] Comments: (yes|no)
  - If you're willing to answer comments about your post, set `comments: true`.
  - Make sure to subscribe to your post comments by clicking on the **Subscribe** link at the very bottom of the post _once_ it's published.

@catlook Please review.

### CODE REVIEW

**Comment by rackernexus** [comment]
:eyes: [Preview](https://staging.developer.rackspace.com/build-368083e8e1/)

**Comment by cyrichardson** [comment]
@catlook Suggested changes for one file here: 
[blog_Troubleshooting hung Oracle databases and sessions with Real-Time ADDM_cyrEdits.docx](https://github.com/rackerlabs/docs-developer-blog/files/2358910/blog_Troubleshooting.hung.Oracle.databases.and.sessions.with.Real-Time.ADDM_cyrEdits.docx)

**Comment by rackernexus** [comment]
HULK [PREVIEW](https://staging.developer.rackspace.com/build-4c39686a9a/)

**Comment by cyrichardson** [comment]
@catlook Here are suggested changes for the other file: 
[blog_Upgrading Oracle Business Intelligence Discoverer- Part 2_cyrEdits.docx](https://github.com/rackerlabs/docs-developer-blog/files/2358954/blog_Upgrading.Oracle.Business.Intelligence.Discoverer-.Part.2_cyrEdits.docx)

**Comment by rackernexus** [comment]
HULK [PREVIEW](https://staging.developer.rackspace.com/build-7be0d722d5/)

**Comment by rackernexus** [comment]
Your content preview [is now ready](https://staging.developer.rackspace.com/build-99f26f9a51/). :bow:

**Pull request merged**
