### PR TITLE
Add post LPN 2: INFODEV-1876

### PR DESCRIPTION
**Pull request by RackerKate**
@cyrichardson Please review.

### CODE REVIEW

**Comment by cyrichardson** [comment]
Got it, @RackerKate.

**Comment by rackernexus** [comment]
Your content preview [is now ready](https://staging.developer.rackspace.com/build-9902ef00ff/). :bow:

**Comment by cyrichardson** [comment]
Change to 2018-06-04-lpn-overview-part1.md approved.

Moving on to Part 2.

**Comment by rackernexus** [comment]
:eyes: [Preview](https://staging.developer.rackspace.com/build-65b375cf4c/)

**Comment by rackernexus** [comment]
Your content preview [is now ready](https://staging.developer.rackspace.com/build-65b375cf4c/). :bow:

**Comment by cyrichardson** [comment]
@RackerKate Suggested changes here: 
[blog_An overview of LPN and shortcuts to mobile Telnet- Part 2_cyrEdits.docx](https://github.com/rackerlabs/docs-developer-blog/files/2073903/blog_An.overview.of.LPN.and.shortcuts.to.mobile.Telnet-.Part.2_cyrEdits.docx)

**Comment by rackernexus** [comment]
Your content preview [is now ready](https://staging.developer.rackspace.com/build-bf06e91207/). :bow:

**Comment by rackernexus** [comment]
Your content preview [is now ready](https://staging.developer.rackspace.com/build-0f10c7fb68/). :bow:

**Comment by rackernexus** [comment]
HULK [PREVIEW](https://staging.developer.rackspace.com/build-0f10c7fb68/)

**Comment by rackernexus** [comment]
If you want to double-check your formatting, check [the preview](https://staging.developer.rackspace.com/build-0ad4aa5090/).

**Comment by rackernexus** [comment]
:eyes: [Preview](https://staging.developer.rackspace.com/build-ce3e11b7a4/)

**Comment by rackernexus** [comment]
:eyes: [Preview](https://staging.developer.rackspace.com/build-ce3e11b7a4/)

**Comment by rackernexus** [comment]
HULK [PREVIEW](https://staging.developer.rackspace.com/build-4c296417cf/)

**Comment by rackernexus** [comment]
HULK [PREVIEW](https://staging.developer.rackspace.com/build-32ef7af968/)

**Comment by rackernexus** [comment]
HULK [PREVIEW](https://staging.developer.rackspace.com/build-f1723d900c/)

**Comment by rackernexus** [comment]
HULK [PREVIEW](https://staging.developer.rackspace.com/build-799667ddb7/)

**Comment by rackernexus** [comment]
:eyes: [Preview](https://staging.developer.rackspace.com/build-799667ddb7/)

**Comment by RackerKate** [comment]
@catlook For your review.

**Comment by rackernexus** [comment]
:eyes: [Preview](https://staging.developer.rackspace.com/build-ffa447d1c6/)

**Comment by rackernexus** [comment]
Your content preview [is now ready](https://staging.developer.rackspace.com/build-2e97297410/). :bow:

**Comment by RackerKate** [comment]
@catlook Can you please re-review? The only thing Smriti suggested that I can't figure out is how to add padding to the table. I've tried a lot of different things; suggestions welcome.

**Comment by rackernexus** [comment]
:mag_right: [Preview](https://staging.developer.rackspace.com/build-ba88203879/)

**Comment by rackernexus** [comment]
Your content preview [is now ready](https://staging.developer.rackspace.com/build-3516f9c708/). :bow:

**Comment by rackernexus** [comment]
:eyes: [Preview](https://staging.developer.rackspace.com/build-3516f9c708/)

**Comment by rackernexus** [comment]
:eyes: [Preview](https://staging.developer.rackspace.com/build-32014751ae/)

**Comment by rackernexus** [comment]
HULK [PREVIEW](https://staging.developer.rackspace.com/build-cd54c2c768/)

**Comment by catlook** [comment]
I had to resort to adding HTML for blank lines, I think.  I have to take care of other stuff for next hour or so.  If you see this before I'm back, look in the blogs for last month or so.  One of mine has a table that I struggled to get spacing right on.  If i'm back first, I'll post here.

**Comment by catlook** [comment]
ok..it was the lacp bonding post.

**Bond interface** &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; | **bond1**
-------------- | -----
Bonding type | 802.3ad
Bonding options | miimon=100,lacp\_rate=fast,xmit\_hash\_policy=layer2+3
Slave interfaces | p5p1 p5p2
MTU | 9000
IP address/prefix | 179.254.0.2/16

&nbsp;

had to add some spaces in teh header to force a gap between columns and a blank line after to create space between table and next line.

**Comment by rackernexus** [comment]
HULK [PREVIEW](https://staging.developer.rackspace.com/build-5fda4bf80f/)

**Comment by rackernexus** [comment]
Your content preview [is now ready](https://staging.developer.rackspace.com/build-966b2a721e/). :bow:

**Comment by rackernexus** [comment]
If you want to double-check your formatting, check [the preview](https://staging.developer.rackspace.com/build-fba76de18f/).

**Comment by rackernexus** [comment]
:mag_right: [Preview](https://staging.developer.rackspace.com/build-fba76de18f/)

**Comment by RackerKate** [comment]
@catlook I managed to get a bit of space in there. Please review/merge.

**Pull request merged**
