### PR TITLE
PLAC: db service blocks initial blog with edits

### PR DESCRIPTION
**Pull request by Sterling463**
In a comment on the pull request, include the following information and check off the list.

 - [ ] Mini bio
  - Soft capped to 75 words
 - [ ] Desired date of publishing
  - Make sure this matches the `date` in the front matter
 - [ ] Social media contact info
 - [ ] Redaction: (yes|no)
  - Allow redaction, editing or structure changes by technical writer staff
 - [ ] Comments: (yes|no)
  - If you're willing to answer comments about your post, set `comments: true`.
  - Make sure to subscribe to your post comments by clicking on the **Subscribe** link at the very bottom of the post _once_ it's published.

@catlook Please review.

### CODE REVIEW

**Comment by rackernexus** [comment]
Build 878 was successful. Staging content [Preview!](https://developer-revs.staging.deconst.org/build-c66e24b3d/). valid for 14 days

**Comment by rackernexus** [comment]
Build 879 was successful. Staging content [Preview!](https://developer-revs.staging.deconst.org/build-e4c54e568/). valid for 14 days

**Comment by rackernexus** [comment]
Build 880 was successful. Staging content [Preview!](https://developer-revs.staging.deconst.org/build-ece21b9f7/). valid for 14 days

**Comment by rackernexus** [comment]
Build 881 was successful. Staging content [Preview!](https://developer-revs.staging.deconst.org/build-6e6921f2d/). valid for 14 days

**Comment by Sterling463** [comment]
@catlook ready for your eyes - won't be published until Friday so no rush. I did notice that there were some issues with spacing between words in the preview that do not reflect what is on my local machine. Hoping this is just a preview issue?

**Comment by rackernexus** [comment]
Build 903 was successful. Staging content [Preview!](https://developer-revs.staging.deconst.org/build-c712d9d4e/). valid for 14 days

**Pull request merged**
