### PR TITLE
Revert "db tuning blog"

### PR DESCRIPTION
**Pull request by catlook**
Reverts rackerlabs/docs-developer-blog#470

accidentally  merged

### CODE REVIEW

**Comment by rackernexus** [comment]
Can one of the admins verify this patch?

**Comment by rackernexus** [comment]
:mag_right: [Preview](https://staging.developer.rackspace.com/build-7fd6eeee33/)

**Comment by cyrichardson** [comment]
@catlook Suggested changes here: 
[blog_Database-performance-tuning_cyrEdits.docx](https://github.com/rackerlabs/docs-developer-blog/files/2770054/blog_Database-performance-tuning_cyrEdits.docx)

**Comment by catlook** [comment]
Have to close this one too...and make new #475.  sheesh.

**Pull request closed without merging**
