### PR TITLE
DO NOT MERGE - THIS IS A TEST: Testing block quotation

### PR DESCRIPTION
**Pull request by cyrichardson**

### CODE REVIEW

**Comment by rackernexus** [comment]
Build 676 was successful. Staging content [Preview!](https://developer-revs.staging.deconst.org/build-147e1e959/). valid for 14 days

**Comment by rackernexus** [comment]
Build 678 was successful. Staging content [Preview!](https://developer-revs.staging.deconst.org/build-bf0472d01/). valid for 14 days

**Comment by cyrichardson** [comment]
Just a test... unable to confirm that the coding (> and a space, one line before and after) publishes properly using deconst for publishing. 

I had Cat review: 
Cat Lookabaugh:grumpycat:  6:55 AM
looks like it didn’t format at all, from what i can tell.  we’d need a dev to work some magic I think.  Or maybe I’m missing it?

Catherine Richardson  7:38 AM
No worries. I’m going to go with documenting it the way you did it in the Style Guide. We know that will work for both md and rst. Thanks for looking!

Closing.

**Comment by cyrichardson** [comment]
build me

**Comment by rackernexus** [comment]
Build 680 was successful. Staging content [Preview!](https://developer-revs.staging.deconst.org/build-bf0472d01/). valid for 14 days

**Comment by cyrichardson** [comment]
The build did work according to notifications in slack:
deconst-control-cicdAPP  11:47 AM
Build 680 for Job: deconst-cicd-content-rackerlabs-docs-developer-blog-pipeline was successful. 
(Check PR 675) 
Target branch:  master 
(Open Staging Preview)

But it is not showing up in staging. 

Just a note that viewing the file here in GitHub does show the block quotation format.

**Comment by rackernexus** [comment]
Build 681 was successful. Staging content [Preview!](https://developer-revs.staging.deconst.org/build-bf0472d01/). valid for 14 days

**Pull request closed without merging**
