### PR TITLE
new post

### PR DESCRIPTION
**Pull request by kgorman**
New post about pandas, jupyter, and some data.gov data about Baltimore Salaries.

### CODE REVIEW

**Comment by kgorman** [comment]
Hrm, gemfile shouldn't have been committed. It was just local mod to make stuff work. hrm.

**Comment by smashwilson** [comment]
Er, also it seems like our build doesn't handle branches pushed into the main repository (as opposed to pull requests submitted from a personal fork) correctly.

I'm in the process of rolling out a correction for this right now, but you caught me right before I started to fix it in the repository. Can you hold off for a few minutes while I get things straightened out? I'll ping you here once it's stable again.

**Comment by kgorman** [comment]
Sure, NP!

**Comment by smashwilson** [comment]
Alright, if you rebase on `master` you should be good :+1:

**Pull request closed without merging**
