### PR TITLE
Added post: MS Certified Azure Administrator Associate

### PR DESCRIPTION
**Pull request by jmbrinkman**
In a comment on the pull request, include the following information and check off the list.

 - [ X] Mini bio: Michiel Brinkman is a Solutions Architect working for Rackspace from Amsterdam, The Netherlands. Multi-cloud certified with a strong engineering background
  - Soft capped to 75 words
 - [ X] Desired date of publishing: 2019-06-12
  - Make sure this matches the `date` in the front matter
 - [ X] Social media contact info: https://www.linkedin.com/in/jmbrinkman1980/
 - [ Yes] Redaction: (yes|no)
  - Allow redaction, editing or structure changes by technical writer staff
 - [ Yes] Comments: (yes|no)
  - If you're willing to answer comments about your post, set `comments: true`.
  - Make sure to subscribe to your post comments by clicking on the **Subscribe** link at the very bottom of the post _once_ it's published.

@catlook Please review.

### CODE REVIEW

**Comment by jmbrinkman** [comment]
In a comment on the pull request, include the following information and check off the list.

 - [ X] Mini bio: Michiel Brinkman is a Solutions Architect working for Rackspace from Amsterdam, The Netherlands. Multi-cloud certified with a strong engineering background
  - Soft capped to 75 words
 - [ X] Desired date of publishing: 2019-06-12
  - Make sure this matches the `date` in the front matter
 - [ X] Social media contact info: https://www.linkedin.com/in/jmbrinkman1980/
 - [ Yes] Redaction: (yes|no)
  - Allow redaction, editing or structure changes by technical writer staff
 - [ Yes] Comments: (yes|no)
  - If you're willing to answer comments about your post, set `comments: true`.
  - Make sure to subscribe to your post comments by clicking on the **Subscribe** link at the very bottom of the post _once_ it's published.

@catlook Please review.

**Comment by rackernexus** [comment]
Build 86 was successful. Staging content [Preview!](https://developer-revs.staging.deconst.org/build-a26f19268/). valid for 14 days

**Comment by rackernexus** [comment]
Build 87 was successful. Staging content [Preview!](https://developer-revs.staging.deconst.org/build-ecc7c8ae7/). valid for 14 days

**Comment by catlook** [comment]
@jmbrinkman Let me know when you're ready for me to take an edit pass through this post :)

**Comment by rackernexus** [comment]
Build 88 was successful. Staging content [Preview!](https://developer-revs.staging.deconst.org/build-82f712b46/). valid for 14 days

**Comment by rackernexus** [comment]
Build 89 was successful. Staging content [Preview!](https://developer-revs.staging.deconst.org/build-e359fbc41/). valid for 14 days

**Pull request merged**
