### PR TITLE
PLAC Armor Anywhere

### PR DESCRIPTION
**Pull request by catlook**
In a comment on the pull request, include the following information and check off the list.

 - [ ] Mini bio
  - Soft capped to 75 words
 - [ ] Desired date of publishing
  - Make sure this matches the `date` in the front matter
 - [ ] Social media contact info
 - [ ] Redaction: (yes|no)
  - Allow redaction, editing or structure changes by technical writer staff
 - [ ] Comments: (yes|no)
  - If you're willing to answer comments about your post, set `comments: true`.
  - Make sure to subscribe to your post comments by clicking on the **Subscribe** link at the very bottom of the post _once_ it's published.

@catlook Please review.

### CODE REVIEW

**Comment by rackernexus** [comment]
Build 823 was successful. Staging content [Preview!](https://developer-revs.staging.deconst.org/build-cffe56713/). valid for 14 days

**Comment by rackernexus** [comment]
Build 824 was successful. Staging content [Preview!](https://developer-revs.staging.deconst.org/build-eb7f6d239/). valid for 14 days

**Comment by catlook** [comment]
3/25: meet with Shannon Ennix and Whiney Parks.  Decided:

1. Shannon or Whitney will provide new CTA URL
2. Corporate blog will publish first, prob wk 4/6 or 4/13.
3. Tech blog will publish as is the following week (with new CTA)
4. Will follow this publish with a deeper dive tech blog, with Info Shannon is providing.
    1. might include why we are integrating AA into portfolio and as part of our PDR solution
    2. Could use info graphics she’s sending
    3. I’m ghost writing it and Shannon is sending me other presentations to draw details from

**Comment by WilliamLoy** [comment]
Build me

**Comment by rackernexus** [comment]
Build 1001 was successful. Staging content [Preview!](https://developer-revs.staging.deconst.org/build-992a5c8ac/). valid for 14 days

**Pull request merged**
