### PR TITLE
Azure webapp endpoint

### PR DESCRIPTION
**Pull request by jrudley**
In a comment on the pull request, include the following information and check off the list.

 - [ ] Mini bio
  - Soft capped to 75 words
 - [ ] Desired date of publishing
  - Make sure this matches the `date` in the front matter
 - [ ] Social media contact info
 - [ ] Redaction: (yes|no) yes
  - Allow redaction, editing or structure changes by technical writer staff
 - [ ] Comments: (yes|no)
  - If you're willing to answer comments about your post, set `comments: true`.
  - Make sure to subscribe to your post comments by clicking on the **Subscribe** link at the very bottom of the post _once_ it's published.

@catlook Please review.

### CODE REVIEW

**Comment by catlook** [comment]
A jrudley original!!! I'm honored :)

**Comment by jrudley** [comment]
build me

**Comment by rackernexus** [comment]
Build 1003 was successful. Staging content [Preview!](https://developer-revs.staging.deconst.org/build-af87e67aa/). valid for 14 days

**Comment by catlook** [comment]
build me

**Comment by rackernexus** [comment]
Build 1006 was successful. Staging content [Preview!](https://developer-revs.staging.deconst.org/build-89a8e8fb0/). valid for 14 days

**Comment by catlook** [comment]
build me

**Comment by rackernexus** [comment]
Build 1008 was successful. Staging content [Preview!](https://developer-revs.staging.deconst.org/build-bb8aa6add/). valid for 14 days

**Comment by catlook** [comment]
build me

**Comment by rackernexus** [comment]
Build 1009 was successful. Staging content [Preview!](https://developer-revs.staging.deconst.org/build-4d7b4af3c/). valid for 14 days

**Pull request merged**
