### PR TITLE
Add Post: MongoDB Tips Part 2

### PR DESCRIPTION
**Pull request by RackerKate**
Waiting for SME review.

### CODE REVIEW

**Comment by rackernexus** [comment]
HULK [PREVIEW](https://staging.developer.rackspace.com/build-82a9795e3c/)

**Comment by rackernexus** [comment]
If you want to double-check your formatting, check [the preview](https://staging.developer.rackspace.com/build-82a9795e3c/).

**Comment by rackernexus** [comment]
Your content preview [is now ready](https://staging.developer.rackspace.com/build-82a9795e3c/). :bow:

**Comment by rackernexus** [comment]
If you want to double-check your formatting, check [the preview](https://staging.developer.rackspace.com/build-f11dd962d2/).

**Comment by rackernexus** [comment]
HULK [PREVIEW](https://staging.developer.rackspace.com/build-a186ae908b/)

**Comment by rackernexus** [comment]
:mag_right: [Preview](https://staging.developer.rackspace.com/build-a186ae908b/)

**Comment by rackernexus** [comment]
:eyes: [Preview](https://staging.developer.rackspace.com/build-50ae9c0fc7/)

**Comment by RackerKate** [comment]
@cyrichardson For your review.

**Comment by cyrichardson** [comment]
@RackerKate - Just a couple of suggested changes: 
[blog_MongoDB tips- Part 2_cyrEdits.docx](https://github.com/rackerlabs/docs-developer-blog/files/2219869/blog_MongoDB.tips-.Part.2_cyrEdits.docx)

**Comment by RackerKate** [comment]
@catlook For your review.

**Comment by rackernexus** [comment]
Your content preview [is now ready](https://staging.developer.rackspace.com/build-9df357a636/). :bow:

**Pull request merged**
