### PR TITLE
Cognos blog

### PR DESCRIPTION
**Pull request by catlook**
In a comment on the pull request, include the following information and check off the list.

 - [ ] Mini bio
  - Soft capped to 75 words
 - [ ] Desired date of publishing
  - Make sure this matches the `date` in the front matter
 - [ ] Social media contact info
 - [ ] Redaction: (yes|no)
  - Allow redaction, editing or structure changes by technical writer staff
 - [ ] Comments: (yes|no)
  - If you're willing to answer comments about your post, set `comments: true`.
  - Make sure to subscribe to your post comments by clicking on the **Subscribe** link at the very bottom of the post _once_ it's published.

@catlook Please review.

### CODE REVIEW

**Comment by rackernexus** [comment]
Your content preview [is now ready](https://staging.developer.rackspace.com/build-19c9e2b6fe/). :bow:

**Comment by cyrichardson** [comment]
@catlook Suggested changes here: 
[blog_New features and performance improvements with TM1 Planning Analytics_cyrEdits.docx](https://github.com/rackerlabs/docs-developer-blog/files/2095866/blog_New.features.and.performance.improvements.with.TM1.Planning.Analytics_cyrEdits.docx)

**Comment by rackernexus** [comment]
:mag_right: [Preview](https://staging.developer.rackspace.com/build-19c9e2b6fe/)

**Comment by rackernexus** [comment]
If you want to double-check your formatting, check [the preview](https://staging.developer.rackspace.com/build-b390bc29a0/).

**Comment by rackernexus** [comment]
:mag_right: [Preview](https://staging.developer.rackspace.com/build-5d373c01f1/)

**Comment by rackernexus** [comment]
:mag_right: [Preview](https://staging.developer.rackspace.com/build-5d373c01f1/)

**Comment by rackernexus** [comment]
HULK [PREVIEW](https://staging.developer.rackspace.com/build-b7bd7feee9/)

**Comment by cyrichardson** [comment]
Round 2 of suggestions for updated blog, @catlook: 
[blog_New features and performance improvements with TM1 Planning Analytics_cyrEdits2.docx](https://github.com/rackerlabs/docs-developer-blog/files/2098701/blog_New.features.and.performance.improvements.with.TM1.Planning.Analytics_cyrEdits2.docx)

**Comment by rackernexus** [comment]
If you want to double-check your formatting, check [the preview](https://staging.developer.rackspace.com/build-32e0fc7147/).

**Pull request merged**
