### PR TITLE
PLAC sap on azure initial version

### PR DESCRIPTION
**Pull request by catlook**
In a comment on the pull request, include the following information and check off the list.

 - [ ] Mini bio
  - Soft capped to 75 words
 - [ ] Desired date of publishing
  - Make sure this matches the `date` in the front matter
 - [ ] Social media contact info
 - [ ] Redaction: (yes|no)
  - Allow redaction, editing or structure changes by technical writer staff
 - [ ] Comments: (yes|no)
  - If you're willing to answer comments about your post, set `comments: true`.
  - Make sure to subscribe to your post comments by clicking on the **Subscribe** link at the very bottom of the post _once_ it's published.

@catlook Please review.

### CODE REVIEW

**Comment by rackernexus** [comment]
Build 857 was successful. Staging content [Preview!](https://developer-revs.staging.deconst.org/build-c7ca7aadb/). valid for 14 days

**Comment by rackernexus** [comment]
Build 864 was successful. Staging content [Preview!](https://developer-revs.staging.deconst.org/build-962a2ca94/). valid for 14 days

**Comment by rackernexus** [comment]
Build 865 was successful. Staging content [Preview!](https://developer-revs.staging.deconst.org/build-1f5728479/). valid for 14 days

**Comment by rackernexus** [comment]
Build 866 was successful. Staging content [Preview!](https://developer-revs.staging.deconst.org/build-862088310/). valid for 14 days

**Comment by rackernexus** [comment]
Build 870 was successful. Staging content [Preview!](https://developer-revs.staging.deconst.org/build-139d00831/). valid for 14 days

**Comment by rackernexus** [comment]
Build 872 was successful. Staging content [Preview!](https://developer-revs.staging.deconst.org/build-000d44f2a/). valid for 14 days

**Comment by rackernexus** [comment]
Build 873 was successful. Staging content [Preview!](https://developer-revs.staging.deconst.org/build-d8d603cd8/). valid for 14 days

**Comment by rackernexus** [comment]
Build 874 was successful. Staging content [Preview!](https://developer-revs.staging.deconst.org/build-77f1ccc16/). valid for 14 days

**Comment by catlook** [comment]
build me

**Comment by rackernexus** [comment]
Build 876 was successful. Staging content [Preview!](https://developer-revs.staging.deconst.org/build-dcdda3f64/). valid for 14 days

**Comment by rackernexus** [comment]
Build 877 was successful. Staging content [Preview!](https://developer-revs.staging.deconst.org/build-f14858a17/). valid for 14 days

**Comment by rackernexus** [comment]
Build 926 was successful. Staging content [Preview!](https://developer-revs.staging.deconst.org/build-099486a36/). valid for 14 days

**Pull request merged**
