### PR TITLE
Add post Hadoop 2.

### PR DESCRIPTION
**Pull request by RackerKate**

### CODE REVIEW

**Comment by rackernexus** [comment]
:eyes: [Preview](https://staging.developer.rackspace.com/build-a71f40be2b/)

**Comment by RackerKate** [comment]
Replaces #290.

**Comment by rackernexus** [comment]
:eyes: [Preview](https://staging.developer.rackspace.com/build-a71f40be2b/)

**Comment by RackerKate** [comment]
@cyrichardson Please review.

**Comment by cyrichardson** [comment]
@RackerKate Some suggestions here: 
[Blog_Hadoop ecosystem basics- Part 2_cyrEdits.docx](https://github.com/rackerlabs/docs-developer-blog/files/2112309/Blog_Hadoop.ecosystem.basics-.Part.2_cyrEdits.docx)

**Comment by rackernexus** [comment]
If you want to double-check your formatting, check [the preview](https://staging.developer.rackspace.com/build-2cd76dc68d/).

**Comment by RackerKate** [comment]
@catlook For your review.

**Comment by catlook** [comment]
reviewing!

**Pull request merged**
