### PR TITLE
Add post hadoop2

### PR DESCRIPTION
**Pull request by RackerKate**

### CODE REVIEW

**Comment by rackernexus** [comment]
HULK [PREVIEW](https://staging.developer.rackspace.com/build-568846a3fc/)

**Comment by rackernexus** [comment]
:eyes: [Preview](https://staging.developer.rackspace.com/build-568846a3fc/)

**Comment by rackernexus** [comment]
:mag_right: [Preview](https://staging.developer.rackspace.com/build-9bc311cf7e/)

**Comment by RackerKate** [comment]
Replaced by #298.

**Pull request closed without merging**
