### PR TITLE
New blog post - Stats from an SSH Honeypot

### PR DESCRIPTION
**Pull request by rbeede**
In a comment on the pull request, include the following information and check off the list.

 - [x] Mini bio
  - Soft capped to 75 words

Rodney Beede is a Cyber Vulnerability Analyst & Penetration Tester for Rackspace Global Enterprise Security.

 - [x] Desired date of publishing
  - 2018-10-23
 - [ ] Social media contact info
 - [x] Redaction:  **YES**
  - Allow redaction, editing or structure changes by technical writer staff
 - [x] Comments: **NO**

@catlook Please review.

### CODE REVIEW

**Comment by rackernexus** [comment]
HULK [PREVIEW](https://staging.developer.rackspace.com/build-d54d024bec/)

**Comment by rbeede** [comment]
Is there a way to make the tables format a little nicer?

**Comment by catlook** [comment]
I ran into this on another blog and had to jump through some hoops, but at least things lined up better.  let me find that ref!!

**Comment by rackernexus** [comment]
:eyes: [Preview](https://staging.developer.rackspace.com/build-7b1d37265e/)

**Comment by catlook** [comment]
Ok that worked ( adding html spaces in the column heading!).  Will submit my edit suggestions to you shortly.  Next time you blog, please make a branch rather than submitting directly to master, if you please :)

**Comment by catlook** [comment]
And sorry for the late response on this!

**Comment by catlook** [comment]
I'll go ahead and make these edits and publish!  Thanks!

**Comment by rackernexus** [comment]
Your content preview [is now ready](https://staging.developer.rackspace.com/build-f9949bd799/). :bow:

**Comment by rbeede** [comment]
The URL in this part didn't turn into a link on the preview.

I used a Linux cloud server with modified SSH server software provided by https://github.com/droberson/ssh-honeypot.git

**Comment by rackernexus** [comment]
Your content preview [is now ready](https://staging.developer.rackspace.com/build-1f012f2532/). :bow:

**Comment by rbeede** [comment]
👍

**Pull request merged**
