### PR TITLE
Aks secrets store driver

### PR DESCRIPTION
**Pull request by jrudley**
In a comment on the pull request, include the following information and check off the list.

 - [ ] Mini bio
  - Soft capped to 75 words
 - [ ] Desired date of publishing
  - 5-13-2020
 - [ ] Social media contact info
 - [ ] Redaction: (yes|no) yes
  - Allow redaction, editing or structure changes by technical writer staff
 - [ ] Comments: (yes|no) yes
  - If you're willing to answer comments about your post, set `comments: true`.
  - Make sure to subscribe to your post comments by clicking on the **Subscribe** link at the very bottom of the post _once_ it's published.

@catlook Please review.

### CODE REVIEW

**Comment by jrudley** [comment]
build me

**Comment by rackernexus** [comment]
Build 1126 was successful. Staging content [Preview!](https://developer-revs.staging.deconst.org/build-e9b6f89c4/). valid for 14 days

**Comment by catlook** [comment]
build me

**Comment by rackernexus** [comment]
Build 1135 was successful. Staging content [Preview!](https://developer-revs.staging.deconst.org/build-bd4018c9a/). valid for 14 days

**Pull request merged**
