### PR TITLE
Add TriCore post "Intro to Oracle Agent Gold": INFODEV-1874

### PR DESCRIPTION
**Pull request by RackerKate**

### CODE REVIEW

**Comment by RackerKate** [comment]
@cyrichardson Please review.

**Comment by cyrichardson** [comment]
On it, @RackerKate.

**Comment by cyrichardson** [comment]
@RackerKate There's no preview because Strider is looking for the .png files. Just an FYI. I'll keep editing the text.

**Comment by rackernexus** [comment]
Your content preview [is now ready](https://staging.developer.rackspace.com/build-335fad1b67/). :bow:

**Comment by rackernexus** [comment]
:mag_right: [Preview](https://staging.developer.rackspace.com/build-335fad1b67/)

**Comment by cyrichardson** [comment]
@RackerKate Suggested changes here: 
[blog_Introduction to Oracle Agent Gold Image feature_cyrEdits.docx](https://github.com/rackerlabs/docs-developer-blog/files/2060237/blog_Introduction.to.Oracle.Agent.Gold.Image.feature_cyrEdits.docx)

Note that I did not move the png files into the docx file, but I did see them in your staging preview.

**Comment by rackernexus** [comment]
:eyes: [Preview](https://staging.developer.rackspace.com/build-418126fcdf/)

**Comment by rackernexus** [comment]
:eyes: [Preview](https://staging.developer.rackspace.com/build-418126fcdf/)

**Comment by rackernexus** [comment]
If you want to double-check your formatting, check [the preview](https://staging.developer.rackspace.com/build-49b7d7841c/).

**Comment by RackerKate** [comment]
@cyrichardson Good to go for your review tomorrow. Thanks!

**Comment by cyrichardson** [comment]
Thanks, @RackerKate. On it.

**Comment by cyrichardson** [comment]
Here are some suggestions: 
[blog_Introduction to Oracle Agent Gold Images_cyrEdits2.docx](https://github.com/rackerlabs/docs-developer-blog/files/2062997/blog_Introduction.to.Oracle.Agent.Gold.Images_cyrEdits2.docx)

**Comment by cyrichardson** [comment]
@RackerKate Suggestions in file above.

**Comment by rackernexus** [comment]
If you want to double-check your formatting, check [the preview](https://staging.developer.rackspace.com/build-eea3b999db/).

**Comment by rackernexus** [comment]
:mag_right: [Preview](https://staging.developer.rackspace.com/build-462a16bc77/)

**Pull request merged**
