### PR TITLE
Sub-bullets, not code blocks

### PR DESCRIPTION
**Pull request by smashwilson**
Let's see if this renders correctly.

### CODE REVIEW

**Comment by rackernexus** [comment]
HULK [PREVIEW](https://staging.developer.rackspace.com/build-a9d8cde856/)

**Comment by rackernexus** [comment]
If you want to double-check your formatting, check [the preview](https://staging.developer.rackspace.com/build-ff862fbd5b/).

**Comment by rackernexus** [comment]
If you want to double-check your formatting, check [the preview](https://staging.developer.rackspace.com/build-9104eeb4b6/).

**Comment by kellyrusk** [comment]
Hi Ash,

Instead of bullet points, nested numbers would be fine too. Do you want to try that, or me?

* top level bullet one
  * sub-bullet  
  * sub-bullet 2 
* top level bullet two  
1. numbered point one
   1. nested numbered point

Regards,

Kelly

**Comment by smashwilson** [comment]
I _think_ I've got it; it looks like this is hitting github/markup#210. I tested it locally, but let's see if the preview agrees.

**Comment by rackernexus** [comment]
Your content preview [is now ready](https://staging.developer.rackspace.com/build-811036a2d6/). :bow:

**Comment by kellyrusk** [comment]
Yes! Looks great. Thanks Ash.

Regards,

Kelly

Kelly Rusk  |  Sitecore Engineer, Critical Application Services

[cid:image001.jpg@01D152D6.444B7590]

Rackspace
kelly.rusk@rackspace.com<mailto:kelly.rusk@rackspace.com>
Office: 210-312-0069
Mobile: 704-491-9801

**Comment by rheidrich62** [comment]
Hello & sorry, I did not get the message: How to create a "i" (i, ii, iii, ...) nested numbered point, instead of bullets?

**Comment by Ralle** [comment]
This still seems somewhat broken to me. Why isn't the nested todo item blue?
screen shot 2019-02-13 at 22 49 58

**Comment by catlook** [comment]
@Ralle The only things that show up blue in published blogs are hyperlinks.  Does that help?

**Comment by Ralle** [comment]
What I meant is that the list items at level 0 are blue, at level 1 they are black. In the editor, not the preview.

**Comment by catlook** [comment]
What editor are you using?  I use BBedit.  I suspect that different editors may treat the content of markdown files differently.  The trick is to learn what your editor shows versus how the content looks when published.  Am I still misunderstanding you?  

When I open the md file in BBedit, no lsit items at any level show up in blue, but bolded content (wrapped in **s) shows up in red.

**Comment by Ralle** [comment]
Um. I must have poked up the wrong hole here. I was sure I was in the repository for [Boostnote](http://boostnote.io).

**Comment by catlook** [comment]
No worries :)

**Pull request merged**
