### PR TITLE
added link for Cassandra

### PR DESCRIPTION
**Pull request by seraphin**
I noticed the missing link to Cassandra. Can someone please verify the modification here will add the link properly?

### CODE REVIEW

**Comment by smashwilson** [comment]
Ah! Good catch. :shipit:

**Comment by smashwilson** [comment]
Hmm, I'm not sure if this did it. I'm investigating locally.

**Comment by smashwilson** [comment]
Found it. That one I have to deploy by hand - it's going out now.

**Comment by smashwilson** [comment]
Yup, that did it:

screen shot 2015-10-12 at 4 17 09 pm

:boom:

Does everything else look okay?

**Comment by rgbkrk** [comment]
Nice!

**Pull request merged**
