### PR TITLE
add file with gravatar links and bio information for contributors

### PR DESCRIPTION
**Pull request by Sterling463**
In a comment on the pull request, include the following information and check off the list.

 - [ ] Mini bio
  - Soft capped to 75 words
 - [ ] Desired date of publishing
  - Make sure this matches the `date` in the front matter
 - [ ] Social media contact info
 - [ ] Redaction: (yes|no)
  - Allow redaction, editing or structure changes by technical writer staff
 - [ ] Comments: (yes|no)
  - If you're willing to answer comments about your post, set `comments: true`.
  - Make sure to subscribe to your post comments by clicking on the **Subscribe** link at the very bottom of the post _once_ it's published.

@catlook Please review.

### CODE REVIEW

**Comment by Sterling463** [comment]
@catlook created a simple text file to track this information. Would you mind taking a look and letting me know if you have any comments?

**Comment by rackernexus** [comment]
Build 464 was successful. Staging content [Preview!](https://developer-revs.staging.deconst.org/build-3584cd1f1/). valid for 14 days

**Comment by rackernexus** [comment]
Build 472 was successful. Staging content [Preview!](https://developer-revs.staging.deconst.org/build-e86ac71f3/). valid for 14 days

**Comment by rackernexus** [comment]
Build 473 was successful. Staging content [Preview!](https://developer-revs.staging.deconst.org/build-54ab9e659/). valid for 14 days

**Comment by rackernexus** [comment]
Build 474 was successful. Staging content [Preview!](https://developer-revs.staging.deconst.org/build-24131ec0b/). valid for 14 days

**Pull request merged**
