### PR TITLE
A simple CICD setup for Terraform providers

### PR DESCRIPTION
**Pull request by mbonig**
In a comment on the pull request, include the following information and check off the list.

 - [x] Mini bio
  - Soft capped to 75 words
 - [x] Desired date of publishing
  - Make sure this matches the `date` in the front matter
 - [x] Social media contact info
 - [no] Redaction: (yes|no)
  - Allow redaction, editing or structure changes by technical writer staff
 - [yes] Comments: (yes|no)
  - If you're willing to answer comments about your post, set `comments: true`.
  - Make sure to subscribe to your post comments by clicking on the **Subscribe** link at the very bottom of the post _once_ it's published.

@catlook Please review.

### CODE REVIEW

**Comment by rackernexus** [comment]
Can one of the admins verify this patch?

**Comment by catlook** [comment]
I'll review this late afternoon and figure out why the build is failing.

**Comment by mbonig** [comment]
Oh no, did I break it again!?

**Comment by mbonig** [comment]
Closing this for now because there are more edits I want to make first and I realize I opened it prematurely.

**Comment by catlook** [comment]
Cool…I’ll keep an eye on the repo ☺


-- Cat Lookabaugh, Information Developer IV
   Rackspace Experience Design Team
Rackspace Hosting – the #1 Managed Cloud Company
Info Dev Team      cat.lookabaugh@rackspace.com
Office: (210) 312-8193   Cell: (210) 364-1060

We should not write so that it is possible for the reader to understand us, but so that it is impossible for him to misunderstand us. - Quintilian, rhetorician (c. 35-100)

Harmony + Learner + Responsibility + Context + Intellection + Arranger + Consistency + Relator + Input + Analytical

**Pull request closed without merging**
