### PR TITLE
The article's title appears twice

### PR DESCRIPTION
**Pull request by miguelgrinberg**

### CODE REVIEW

**Comment by ktbartholomew** [comment]
@miguelgrinberg You can escape all of the curly braces in a much more readable way by wrapping the relevant sections in the `{% raw %}` and `{% endraw %}` tags.

**Comment by miguelgrinberg** [comment]
@ktbartholomew Thanks. Let me know if this looks better.

**Comment by rgbkrk** [comment]
LGTM

**Comment by miguelgrinberg** [comment]
@rgbkrk Oh, crap. Missed a couple of quotes, just noticed it in the visual diff here. You are too fast. :)

**Comment by rgbkrk** [comment]
Another day, another PR.

**Pull request merged**
