### PR TITLE
nthis should be all

### PR DESCRIPTION
**Pull request by jmbrinkman**
- [x] Mini bio - already provided
 - [x] Desired date of publishing 2019-07-02
 - [x] Social media contact info - already provided
 - [x] Redaction: yes
 - [x] Comments: yes

@catlook Please review.

### CODE REVIEW

**Comment by rackernexus** [comment]
Build 110 was successful. Staging content [Preview!](https://developer-revs.staging.deconst.org/build-22ae2a11d/). valid for 14 days

**Comment by rackernexus** [comment]
Build 111 was successful. Staging content [Preview!](https://developer-revs.staging.deconst.org/build-6c1181681/). valid for 14 days

**Comment by rackernexus** [comment]
Build 112 was successful. Staging content [Preview!](https://developer-revs.staging.deconst.org/build-e8fe3fc84/). valid for 14 days

**Comment by rackernexus** [comment]
Build 113 was successful. Staging content [Preview!](https://developer-revs.staging.deconst.org/build-911572858/). valid for 14 days

**Comment by rackernexus** [comment]
Build 114 was successful. Staging content [Preview!](https://developer-revs.staging.deconst.org/build-de5b9c294/). valid for 14 days

**Comment by catlook** [comment]
build me

**Comment by rackernexus** [comment]
Build 115 was successful. Staging content [Preview!](https://developer-revs.staging.deconst.org/build-de5b9c294/). valid for 14 days

**Comment by catlook** [comment]
Ok..can't get the table to render properly, so I'm converting it to a list format (in a few hours).  If everything else is good, I'll publish it in the morning!  @jmbrinkman thanks for the submission!!

**Comment by rackernexus** [comment]
Build 116 was successful. Staging content [Preview!](https://developer-revs.staging.deconst.org/build-dde717989/). valid for 14 days

**Comment by rackernexus** [comment]
Build 117 was successful. Staging content [Preview!](https://developer-revs.staging.deconst.org/build-82514916f/). valid for 14 days

**Comment by catlook** [comment]
Ok, @jmbrinkman, I think I've got it.  The table idea was more elegant, but I couldn't get it to format properly, so I think this works.  I'll publish it in the morning!  Let me know if you'd like any changes!!

**Pull request merged**
