### PR TITLE
ADF blog

### PR DESCRIPTION
**Pull request by catlook**
In a comment on the pull request, include the following information and check off the list.

 - [ ] Mini bio
  - Soft capped to 75 words
 - [ ] Desired date of publishing
  - Make sure this matches the `date` in the front matter
 - [ ] Social media contact info
 - [ ] Redaction: (yes|no)
  - Allow redaction, editing or structure changes by technical writer staff
 - [ ] Comments: (yes|no)
  - If you're willing to answer comments about your post, set `comments: true`.
  - Make sure to subscribe to your post comments by clicking on the **Subscribe** link at the very bottom of the post _once_ it's published.

@catlook Please review.

### CODE REVIEW

**Comment by catlook** [comment]
build me

**Comment by rackernexus** [comment]
Build 653 was successful. Staging content [Preview!](https://developer-revs.staging.deconst.org/build-dcf1a888d/). valid for 14 days

**Comment by rackernexus** [comment]
Build 654 was successful. Staging content [Preview!](https://developer-revs.staging.deconst.org/build-8caee3557/). valid for 14 days

**Comment by rackernexus** [comment]
Build 655 was successful. Staging content [Preview!](https://developer-revs.staging.deconst.org/build-f48e6c7cc/). valid for 14 days

**Comment by rackernexus** [comment]
Build 656 was successful. Staging content [Preview!](https://developer-revs.staging.deconst.org/build-06f5c611e/). valid for 14 days

**Comment by rackernexus** [comment]
Build 657 was successful. Staging content [Preview!](https://developer-revs.staging.deconst.org/build-1016f4a27/). valid for 14 days

**Comment by rackernexus** [comment]
Build 658 was successful. Staging content [Preview!](https://developer-revs.staging.deconst.org/build-522bfc5dc/). valid for 14 days

**Comment by rackernexus** [comment]
Build 659 was successful. Staging content [Preview!](https://developer-revs.staging.deconst.org/build-522bfc5dc/). valid for 14 days

**Comment by rackernexus** [comment]
Build 660 was successful. Staging content [Preview!](https://developer-revs.staging.deconst.org/build-c7693e0c5/). valid for 14 days

**Comment by rackernexus** [comment]
Build 661 was successful. Staging content [Preview!](https://developer-revs.staging.deconst.org/build-f884c5f71/). valid for 14 days

**Pull request merged**
