### PR TITLE
Markdown touchups

### PR DESCRIPTION
**Pull request by smashwilson**
Markdown and asset touchups on a few recent blog posts.

### CODE REVIEW

**Comment by rackernexus** [comment]
Your content preview [is now ready](https://staging.developer.rackspace.com/build-39a44db6ed/). :bow:

**Comment by rackernexus** [comment]
If you want to double-check your formatting, check [the preview](https://staging.developer.rackspace.com/build-d17ef20a78/).

**Comment by rackernexus** [comment]
:mag_right: [Preview](https://staging.developer.rackspace.com/build-1b42908999/)

**Comment by rackernexus** [comment]
If you want to double-check your formatting, check [the preview](https://staging.developer.rackspace.com/build-82ca34e20f/).

**Comment by smashwilson** [comment]
:+1:

**Pull request merged**
