### PR TITLE
PLAC clouthhealth blog

### PR DESCRIPTION
**Pull request by catlook**
In a comment on the pull request, include the following information and check off the list.

 - [ ] Mini bio
  - Soft capped to 75 words
 - [ ] Desired date of publishing
  - Make sure this matches the `date` in the front matter
 - [ ] Social media contact info
 - [ ] Redaction: (yes|no)
  - Allow redaction, editing or structure changes by technical writer staff
 - [ ] Comments: (yes|no)
  - If you're willing to answer comments about your post, set `comments: true`.
  - Make sure to subscribe to your post comments by clicking on the **Subscribe** link at the very bottom of the post _once_ it's published.

@catlook Please review.

### CODE REVIEW

**Comment by catlook** [comment]
build me

**Comment by rackernexus** [comment]
Build 617 was successful. Staging content [Preview!](https://developer-revs.staging.deconst.org/build-8d5285526/). valid for 14 days

**Comment by rackernexus** [comment]
Build 618 was successful. Staging content [Preview!](https://developer-revs.staging.deconst.org/build-25dfbaa00/). valid for 14 days

**Comment by rackernexus** [comment]
Build 619 was successful. Staging content [Preview!](https://developer-revs.staging.deconst.org/build-83b03829f/). valid for 14 days

**Comment by rackernexus** [comment]
Build 620 was successful. Staging content [Preview!](https://developer-revs.staging.deconst.org/build-1334037a1/). valid for 14 days

**Comment by catlook** [comment]
FYI: build still failing.
Traceback (most recent call last):
  File "/opt/rh/rh-python36/root/usr/lib64/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/opt/rh/rh-python36/root/usr/lib64/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/tmp/workspace/deconst-cicd-content-rackerlabs-docs-cloud-identity-pipeline/preparer-sphinx/deconstrst/__main__.py", line 5, in <module>
    main()
  File "/tmp/workspace/deconst-cicd-content-rackerlabs-docs-cloud-identity-pipeline/preparer-sphinx/deconstrst/__init__.py", line 43, in main
    status = build(srcdir, destdir)
  File "/tmp/workspace/deconst-cicd-content-rackerlabs-docs-cloud-identity-pipeline/preparer-sphinx/deconstrst/deconstrst.py", line 32, in build
    parallel=1)
  File "/opt/app-root/lib/python3.6/site-packages/sphinx/application.py", line 149, in __init__
    self.setup_extension(extension)
  File "/opt/app-root/lib/python3.6/site-packages/sphinx/application.py", line 458, in setup_extension
    mod = __import__(extension, None, None, ['setup'])
  File "/opt/app-root/lib/python3.6/site-packages/chios/bolditalic/__init__.py", line 32, in <module>
    logger = logging.getLogger(__name__)
AttributeError: module 'sphinx.util.logging' has no attribute 'getLogger'
script returned exit code 1

**Pull request merged**
