### PR TITLE
cassandra backup and restore

### PR DESCRIPTION
**Pull request by catlook**
In a comment on the pull request, include the following information and check off the list.

 - [ ] Mini bio
  - Soft capped to 75 words
 - [ ] Desired date of publishing
  - Make sure this matches the `date` in the front matter
 - [ ] Social media contact info
 - [ ] Redaction: (yes|no)
  - Allow redaction, editing or structure changes by technical writer staff
 - [ ] Comments: (yes|no)
  - If you're willing to answer comments about your post, set `comments: true`.
  - Make sure to subscribe to your post comments by clicking on the **Subscribe** link at the very bottom of the post _once_ it's published.

@catlook Please review.

### CODE REVIEW

**Comment by rackernexus** [comment]
Build 143 was successful. Staging content [Preview!](https://developer-revs.staging.deconst.org/build-27d52d9c4/). valid for 14 days

**Comment by cyrichardson** [comment]
@catlook  Please review and see if you agree.

**Comment by rackernexus** [comment]
Build 145 was successful. Staging content [Preview!](https://developer-revs.staging.deconst.org/build-29e62ea1f/). valid for 14 days

**Comment by rackernexus** [comment]
Build 146 was successful. Staging content [Preview!](https://developer-revs.staging.deconst.org/build-fcc2d829f/). valid for 14 days

**Pull request merged**
