### PR TITLE
Sql vm resource provider

### PR DESCRIPTION
**Pull request by jrudley**
In a comment on the pull request, include the following information and check off the list.

 - [ ] Mini bio
  - Soft capped to 75 words
 - [ ] Desired date of publishing
  - Make sure this matches the `date` in the front matter
 - [ ] Social media contact info
 - [ ] Redaction: (yes|no)yes
  - Allow redaction, editing or structure changes by technical writer staff
 - [ ] Comments: (yes|no)yes
  - If you're willing to answer comments about your post, set `comments: true`.
  - Make sure to subscribe to your post comments by clicking on the **Subscribe** link at the very bottom of the post _once_ it's published.

@catlook Please review.

### CODE REVIEW

**Comment by rackernexus** [comment]
Build 667 was successful. Staging content [Preview!](https://developer-revs.staging.deconst.org/build-1b104a9d5/). valid for 14 days

**Comment by rackernexus** [comment]
Build 668 was successful. Staging content [Preview!](https://developer-revs.staging.deconst.org/build-4602341e5/). valid for 14 days

**Comment by rackernexus** [comment]
Build 669 was successful. Staging content [Preview!](https://developer-revs.staging.deconst.org/build-0d374f7b8/). valid for 14 days

**Comment by catlook** [comment]
@jrudley all good? Any adjustments needed?

**Comment by rackernexus** [comment]
Build 672 was successful. Staging content [Preview!](https://developer-revs.staging.deconst.org/build-6a40e2d0a/). valid for 14 days

**Comment by rackernexus** [comment]
Build 673 was successful. Staging content [Preview!](https://developer-revs.staging.deconst.org/build-c3f97587a/). valid for 14 days

**Comment by catlook** [comment]
Cat Lookabaugh: 1/28  12:25 PM
Check out your blog…edits are applied!  If you like it, I’ll publish

Jimmy Rudley  5:18 PM
Hi sorry i am out today. I did look and it is perfect!

Cat Lookabaugh:  6:12 PM
No worries..will pub tomorrow!

Jimmy Rudley  6:15 PM
thx

**Pull request merged**
