### PR TITLE
Create 2019-11-11-cloud-servers-do-i-get-charged-when-my-server-is-sh…

### PR DESCRIPTION
**Pull request by BadCrumpany**
…utdown?.md

In a comment on the pull request, include the following information and check off the list.

 - Desired date of publishing - 11/11/2019
 - Make sure this matches the `date` in the front matter
 - Social media contact info N/A
 - Redaction: (yes|no) no
  - Allow redaction, editing or structure changes by technical writer staff yes
 -  Comments: yes
 - If you're willing to answer comments about your post, set `comments: true`. 
- Make sure to subscribe to your post comments by clicking on the **Subscribe** link at the very bottom of the post _once_ it's published.

@catlook Please review.

### CODE REVIEW

**Comment by rackernexus** [comment]
Build 344 was successful. Staging content [Preview!](https://developer-revs.staging.deconst.org/build-32134e5e1/). valid for 14 days

**Comment by rackernexus** [comment]
Build 351 was successful. Staging content [Preview!](https://developer-revs.staging.deconst.org/build-90f1de38a/). valid for 14 days

**Comment by rackernexus** [comment]
Build 353 was successful. Staging content [Preview!](https://developer-revs.staging.deconst.org/build-b9efaec67/). valid for 14 days

**Comment by rackernexus** [comment]
Build 354 was successful. Staging content [Preview!](https://developer-revs.staging.deconst.org/build-ba3b315fc/). valid for 14 days

**Comment by rackernexus** [comment]
Build 356 was successful. Staging content [Preview!](https://developer-revs.staging.deconst.org/build-3e919f5cd/). valid for 14 days

**Comment by catlook** [comment]
closing this one.  we agree it's better suited as a how-to article!

**Pull request closed without merging**
