### PR TITLE
Personalizing

### PR DESCRIPTION
**Pull request by Sterling463**
In a comment on the pull request, include the following information and check off the list.

 - [ ] Mini bio
  - Soft capped to 75 words
 - [ ] Desired date of publishing
  - Make sure this matches the `date` in the front matter
 - [ ] Social media contact info
 - [ ] Redaction: (yes|no)
  - Allow redaction, editing or structure changes by technical writer staff
 - [ ] Comments: (yes|no)
  - If you're willing to answer comments about your post, set `comments: true`.
  - Make sure to subscribe to your post comments by clicking on the **Subscribe** link at the very bottom of the post _once_ it's published.

@catlook Please review.

### CODE REVIEW

**Comment by Sterling463** [comment]
@cyrichardson Would you mind reviewing this PR?

**Comment by cyrichardson** [comment]
On it, @Sterling463.

**Comment by Sterling463** [comment]
@catlook Your turn please!

**Comment by rackernexus** [comment]
Build 476 was successful. Staging content [Preview!](https://developer-revs.staging.deconst.org/build-315866cfc/). valid for 14 days

**Comment by rackernexus** [comment]
Build 477 was successful. Staging content [Preview!](https://developer-revs.staging.deconst.org/build-f11c4afed/). valid for 14 days

**Comment by rackernexus** [comment]
Build 478 was successful. Staging content [Preview!](https://developer-revs.staging.deconst.org/build-954412d72/). valid for 14 days

**Comment by rackernexus** [comment]
Build 480 was successful. Staging content [Preview!](https://developer-revs.staging.deconst.org/build-fa48c84ed/). valid for 14 days

**Comment by rackernexus** [comment]
Build 482 was successful. Staging content [Preview!](https://developer-revs.staging.deconst.org/build-f3d169f34/). valid for 14 days

**Comment by rackernexus** [comment]
Build 483 was successful. Staging content [Preview!](https://developer-revs.staging.deconst.org/build-5d77c6f0f/). valid for 14 days

**Comment by Sterling463** [comment]
Build me

**Comment by rackernexus** [comment]
Build 507 was successful. Staging content [Preview!](https://developer-revs.staging.deconst.org/build-2a4ef0e6d/). valid for 14 days

**Pull request merged**
