### PR TITLE
Add content and images for new Office 365 migration post.

### PR DESCRIPTION
**Pull request by RackerKate**
Needs SME review.

### CODE REVIEW

**Comment by rackernexus** [comment]
:mag_right: [Preview](https://staging.developer.rackspace.com/build-31023a3685/)

**Comment by rackernexus** [comment]
Your content preview [is now ready](https://staging.developer.rackspace.com/build-8778b0876a/). :bow:

**Comment by RackerKate** [comment]
Sent to SME for review on 7/26.

**Comment by RackerKate** [comment]
@cyrichardson Another for your review please.

**Comment by cyrichardson** [comment]
@RackerKate A few suggestions here: 
[blog_Office365migration types-What'sbBestForMe?_cyrEdits.docx](https://github.com/rackerlabs/docs-developer-blog/files/2242235/blog_Office365migration.types-What.sbBestForMe._cyrEdits.docx)

**Comment by rackernexus** [comment]
If you want to double-check your formatting, check [the preview](https://staging.developer.rackspace.com/build-790f68fc39/).

**Pull request merged**
