### PR TITLE
PLAC rgc on aws post

### PR DESCRIPTION
**Pull request by catlook**
In a comment on the pull request, include the following information and check off the list.

 - [ ] Mini bio
  - Soft capped to 75 words
 - [ ] Desired date of publishing
  - Make sure this matches the `date` in the front matter
 - [ ] Social media contact info
 - [ ] Redaction: (yes|no)
  - Allow redaction, editing or structure changes by technical writer staff
 - [ ] Comments: (yes|no)
  - If you're willing to answer comments about your post, set `comments: true`.
  - Make sure to subscribe to your post comments by clicking on the **Subscribe** link at the very bottom of the post _once_ it's published.

@catlook Please review.

### CODE REVIEW

**Comment by rackernexus** [comment]
Build 858 was successful. Staging content [Preview!](https://developer-revs.staging.deconst.org/build-a0a9e9641/). valid for 14 days

**Comment by rackernexus** [comment]
Build 871 was successful. Staging content [Preview!](https://developer-revs.staging.deconst.org/build-a74d6f093/). valid for 14 days

**Comment by rackernexus** [comment]
Build 906 was successful. Staging content [Preview!](https://developer-revs.staging.deconst.org/build-d9ee45b17/). valid for 14 days

**Comment by rackernexus** [comment]
Build 950 was successful. Staging content [Preview!](https://developer-revs.staging.deconst.org/build-a7d8c6ea2/). valid for 14 days

**Comment by rackernexus** [comment]
Build 951 was successful. Staging content [Preview!](https://developer-revs.staging.deconst.org/build-9f5130dbb/). valid for 14 days

**Comment by catlook** [comment]
build me

**Comment by rackernexus** [comment]
Build 953 was successful. Staging content [Preview!](https://developer-revs.staging.deconst.org/build-d177b5d6a/). valid for 14 days

**Pull request merged**
