### PR TITLE
Add post about styling gertty

### PR DESCRIPTION
**Pull request by sigmavirus24**
In a comment on the pull request, include the following information and check off the list.

 - [x] Mini bio
  - Soft capped to 75 words
 - [x] Desired date of publishing
  - Make sure this matches the `date` in the front matter
 - [x] Social media contact info
 - [x] Redaction: (**yes**|no)
  - Allow redaction, editing or structure changes by technical writer staff
 - [x] Comments: (yes|**no**)
  - If you're willing to answer comments about your post, set `comments: true`.
  - Make sure to subscribe to your post comments by clicking on the **Subscribe** link at the very bottom of the post _once_ it's published.

@catlook Please review.

### CODE REVIEW

**Comment by rackernexus** [comment]
If you want to double-check your formatting, check [the preview](https://staging.developer.rackspace.com/build-f8649d210a/).

**Comment by sigmavirus24** [comment]
# Mini bio

Ian Cordasco is a Racker of 2.5 years in the Private Cloud Engineering group. He's a core reviewer of OpenStack Glance, Bandit, Hacking, and Craton. He maintains Requests, Flake8, PyYAML, and LibYAML in his free time and helps administer the Python Code Quality Authority.

# Desired date of publishing

Tomorrow? Today? I am flexible. I threw tomorrow's date in there to be safe.

# Social media contact info

- @sigmavirus24 on twitter
- /u/sigmavirus24 on Reddit
- Need others?

# Redaction: 

Yes. 

# Comments

No

---

cc @asettle

**Comment by rackernexus** [comment]
Your content preview [is now ready](https://staging.developer.rackspace.com/build-82ff4c8002/). :bow:

**Comment by catlook** [comment]
Ian, I see the PR is closed...do you want this up on the dev blog?

**Comment by sigmavirus24** [comment]
@catlook I would love to have this up on the dev blog, but I was led to believe y'all only want original content (which is fine by me) so I closed it. =) Let me know if I heard incorrectly and I'll be happy to reopen it.

**Pull request closed without merging**
