### PR TITLE
new security blog about software development and credential rotation

### PR DESCRIPTION
**Pull request by rbeede**
In a comment on the pull request, include the following information and check off the list.

 - [x] Mini bio

I am a security penetration tester for Rackspace.  I have been involved in computer security for 10+ years.  My other work includes cloud security architecture design as well as speaking at security conferences.  You can find more at my personal website at https://www.rodneybeede.com/

 - [x] Desired date of publishing

August 6, 2018

 - [ ] Social media contact info

None

 - [x] Redaction: (yes)

yes

 - [x] Comments: (yes)

yes

@catlook Please review.

### CODE REVIEW

**Comment by rackernexus** [comment]
:eyes: [Preview](https://staging.developer.rackspace.com/build-0c7f3d5989/)

**Comment by rbeede** [comment]
Some of the markup did not translate.

Will need to fix before publishing.

**Comment by catlook** [comment]
i see what you're talking about.  Pretty sure I can fix those.

**Comment by rackernexus** [comment]
Your content preview [is now ready](https://staging.developer.rackspace.com/build-0c7f3d5989/). :bow:

**Comment by rackernexus** [comment]
:eyes: [Preview](https://staging.developer.rackspace.com/build-7577dae26a/)

**Comment by rackernexus** [comment]
HULK [PREVIEW](https://staging.developer.rackspace.com/build-b1396abea9/)

**Comment by catlook** [comment]
Ok...check this out!  I fixed the formatting and made some basic readability edits.  Usually, I submit those to you (ad the other contributors) to make. However, since I was in there anyway, I went ahead and made the edits.  Give it a read through and make sure I didn't mess with your meaning or intent!

**Comment by rbeede** [comment]
Looks great!   Thanks!

**Comment by rackernexus** [comment]
:eyes: [Preview](https://staging.developer.rackspace.com/build-b1396abea9/)

**Pull request merged**
