### PR TITLE
Geofencing

### PR DESCRIPTION
**Pull request by Sterling463**
In a comment on the pull request, include the following information and check off the list.

 - [ ] Mini bio
  - Soft capped to 75 words
 - [ ] Desired date of publishing
  - Make sure this matches the `date` in the front matter
 - [ ] Social media contact info
 - [ ] Redaction: (yes|no)
  - Allow redaction, editing or structure changes by technical writer staff
 - [ ] Comments: (yes|no)
  - If you're willing to answer comments about your post, set `comments: true`.
  - Make sure to subscribe to your post comments by clicking on the **Subscribe** link at the very bottom of the post _once_ it's published.

@cyrichardson  Would you mind reviewing at your convenience?

### CODE REVIEW

**Comment by rackernexus** [comment]
Build 391 was successful. Staging content [Preview!](https://developer-revs.staging.deconst.org/build-be0975778/). valid for 14 days

**Comment by cyrichardson** [comment]
@Sterling463 On it!

**Comment by Sterling463** [comment]
@catlook would you mind taking a look at this article?

**Comment by catlook** [comment]
on it...fyi the fail is the slack integration.

**Comment by catlook** [comment]
build me

**Comment by rackernexus** [comment]
Build 396 was successful. Staging content [Preview!](https://developer-revs.staging.deconst.org/build-9c89c875e/). valid for 14 days

**Pull request merged**
