### PR TITLE
Initial rewrite of the Pyton Getting started page.  DO NOT MERGE WIP.

### PR DESCRIPTION
**Pull request by davisaaronj**
In a comment on the pull request, include the following information and check off the list.
Racker  in public cloud working on SDK docs for Developer.rackspace.com this is not ready to be merged yet.
 
Any Comments welcome I did include YAML but not sure if that will work yet testing that my changes look ok for the moment.  

@catlook Please review and provide guidance.  Not ready to publish though.

### CODE REVIEW

**Comment by rackernexus** [comment]
:mag_right: [Preview](https://staging.developer.rackspace.com/build-da775570d2/)

**Comment by rackernexus** [comment]
HULK [PREVIEW](https://staging.developer.rackspace.com/build-ee3c9432f7/)

**Comment by catlook** [comment]
How's this one going?  Ready to publish?  No rush, just wondering :)

**Comment by davisaaronj** [comment]
Closing for now.

**Pull request closed without merging**
