### PR TITLE
Add post ODB tuning part 2: INFODEV-2423

### PR DESCRIPTION
**Pull request by RackerKate**

### CODE REVIEW

**Comment by rackernexus** [comment]
HULK [PREVIEW](https://staging.developer.rackspace.com/build-598dbd1e69/)

**Comment by rackernexus** [comment]
If you want to double-check your formatting, check [the preview](https://staging.developer.rackspace.com/build-7cc2942f5d/).

**Comment by rackernexus** [comment]
Your content preview [is now ready](https://staging.developer.rackspace.com/build-a91060663e/). :bow:

**Comment by RackerKate** [comment]
@cyrichardson For your review.

**Comment by cyrichardson** [comment]
@RackerKate On it!

**Comment by cyrichardson** [comment]
Just a few suggestions, @RackerKate:
[blog_New performance-tuning features of Oracle Database 12c Release 12.1.0.0- Part 2_cyrEdits.docx](https://github.com/rackerlabs/docs-developer-blog/files/2439346/blog_New.performance-tuning.features.of.Oracle.Database.12c.Release.12.1.0.0-.Part.2_cyrEdits.docx)

**Comment by rackernexus** [comment]
:eyes: [Preview](https://staging.developer.rackspace.com/build-a91060663e/)

**Comment by rackernexus** [comment]
Your content preview [is now ready](https://staging.developer.rackspace.com/build-9e09040da4/). :bow:

**Comment by RackerKate** [comment]
@catlook For your review. Can you publish tomorrow?

**Pull request merged**
