### PR TITLE
update blogs to include author avatar, if available

### PR DESCRIPTION
**Pull request by catlook**
In a comment on the pull request, include the following information and check off the list.

 - [ ] Mini bio
  - Soft capped to 75 words
 - [ ] Desired date of publishing
  - Make sure this matches the `date` in the front matter
 - [ ] Social media contact info
 - [ ] Redaction: (yes|no)
  - Allow redaction, editing or structure changes by technical writer staff
 - [ ] Comments: (yes|no)
  - If you're willing to answer comments about your post, set `comments: true`.
  - Make sure to subscribe to your post comments by clicking on the **Subscribe** link at the very bottom of the post _once_ it's published.

@catlook Please review.

### CODE REVIEW

**Comment by rackernexus** [comment]
Build 534 was successful. Staging content [Preview!](https://developer-revs.staging.deconst.org/build-06c9bf8e6/). valid for 14 days

**Comment by rackernexus** [comment]
Build 535 was successful. Staging content [Preview!](https://developer-revs.staging.deconst.org/build-06a213d90/). valid for 14 days

**Comment by rackernexus** [comment]
Build 536 was successful. Staging content [Preview!](https://developer-revs.staging.deconst.org/build-3dc0c9686/). valid for 14 days

**Comment by catlook** [comment]
build me

**Comment by rackernexus** [comment]
Build 538 was successful. Staging content [Preview!](https://developer-revs.staging.deconst.org/build-769238d05/). valid for 14 days

**Comment by rackernexus** [comment]
Build 539 was successful. Staging content [Preview!](https://developer-revs.staging.deconst.org/build-e9b1a8229/). valid for 14 days

**Pull request merged**
