### PR TITLE
Removing signup markup

### PR DESCRIPTION
**Pull request by kenperkins**
For `/signup`.

### CODE REVIEW

**Comment by rackernexus** [comment]
HULK [PREVIEW](https://staging.developer.rackspace.com/build-0c5c12a7f6/)

**Comment by kenperkins** [comment]
@smashwilson I was under the impression that https://staging.developer.rackspace.com/build-0c5c12a7f6/signup/ should not work since this is keyed to a specific build and I've removed that file in the commit.

**Comment by smashwilson** [comment]
It's finding the `https://github.com/rackerlabs/docs-developer-blog/signup` envelope in the upstream content service.

**Comment by kenperkins** [comment]
Right. I forgot it proxies back.

**Comment by kenperkins** [comment]
Self merge yolo

**Pull request merged**
