### PR TITLE
Content Fanatic - Create 2019-11-11-a-fanatical-experience-means-a-wi…

### PR DESCRIPTION
**Pull request by BadCrumpany**
…n-for-customers-a-support-perspective.md

In a comment on the pull request, include the following information and check off the list.

 - Desired date of publishing 11-11-2019
 - Make sure this matches the `date` in the front matter
 - [ ] Social media contact info
 - [ ] Redaction: no
  - Allow redaction, editing or structure changes by technical writer staff yes
 - [ ] Comments: yes
  - If you're willing to answer comments about your post, set `comments: true`.
  - Make sure to subscribe to your post comments by clicking on the **Subscribe** link at the very bottom of the post _once_ it's published.

@catlook Please review.

### CODE REVIEW

**Comment by rackernexus** [comment]
Build 345 was successful. Staging content [Preview!](https://developer-revs.staging.deconst.org/build-3c1f28ed7/). valid for 14 days

**Comment by rackernexus** [comment]
Build 346 was successful. Staging content [Preview!](https://developer-revs.staging.deconst.org/build-d761a24c1/). valid for 14 days

**Comment by rackernexus** [comment]
Build 347 was successful. Staging content [Preview!](https://developer-revs.staging.deconst.org/build-36881b1ad/). valid for 14 days

**Comment by rackernexus** [comment]
Build 348 was successful. Staging content [Preview!](https://developer-revs.staging.deconst.org/build-b9f03e037/). valid for 14 days

**Comment by rackernexus** [comment]
Build 350 was successful. Staging content [Preview!](https://developer-revs.staging.deconst.org/build-bad784dc7/). valid for 14 days

**Comment by rackernexus** [comment]
Build 352 was successful. Staging content [Preview!](https://developer-revs.staging.deconst.org/build-2a75dec17/). valid for 14 days

**Comment by rackernexus** [comment]
Build 355 was successful. Staging content [Preview!](https://developer-revs.staging.deconst.org/build-7a45d2c22/). valid for 14 days

**Comment by edwardjrp** [comment]
build me

**Comment by rackernexus** [comment]
Build 368 was successful. Staging content [Preview!](https://developer-revs.staging.deconst.org/build-9bd690944/). valid for 14 days

**Pull request merged**
