### PR TITLE
Roadblocks

### PR DESCRIPTION
**Pull request by Sterling463**
In a comment on the pull request, include the following information and check off the list.

 - [ ] Mini bio
  - Soft capped to 75 words
 - [ ] Desired date of publishing
  - Make sure this matches the `date` in the front matter
 - [ ] Social media contact info
 - [ ] Redaction: (yes|no)
  - Allow redaction, editing or structure changes by technical writer staff
 - [ ] Comments: (yes|no)
  - If you're willing to answer comments about your post, set `comments: true`.
  - Make sure to subscribe to your post comments by clicking on the **Subscribe** link at the very bottom of the post _once_ it's published.

@cyrichardson Please review

### CODE REVIEW

**Comment by cyrichardson** [comment]
On it, @Sterling463!

**Comment by rackernexus** [comment]
Build 380 was successful. Staging content [Preview!](https://developer-revs.staging.deconst.org/build-1d0db5b25/). valid for 14 days

**Comment by catlook** [comment]
on it!

**Comment by rackernexus** [comment]
Build 384 was successful. Staging content [Preview!](https://developer-revs.staging.deconst.org/build-220885eab/). valid for 14 days

**Comment by rackernexus** [comment]
Build 385 was successful. Staging content [Preview!](https://developer-revs.staging.deconst.org/build-44bda4f19/). valid for 14 days

**Pull request merged**
