### PR TITLE
changed backtick code blocks to indention

### PR DESCRIPTION
**Pull request by ncoble**
Fixing formatting issues with my post.

### CODE REVIEW

**Comment by ktbartholomew** [comment]
@ncoble what problem are you trying to solve here? The backtick notation for code blocks is generally preferred.

**Comment by ncoble** [comment]
@ktbartholomew  The code blocks are showing up inline.  And the "#" are not being escaped inside the code blocks.  Any direction is appreciated.   Thanks!

**Comment by smashwilson** [comment]
:thought_balloon: You might need an extra blank line around your backticks, perhaps?

**Comment by ktbartholomew** [comment]
:+1: yep, code blocks need a blank line before/after.

**Comment by ncoble** [comment]
Thanks guys.

**Pull request merged**
