### PR TITLE
cns for aws

### PR DESCRIPTION
**Pull request by catlook**
In a comment on the pull request, include the following information and check off the list.

 - [ ] Mini bio
  - Soft capped to 75 words
 - [ ] Desired date of publishing
  - Make sure this matches the `date` in the front matter
 - [ ] Social media contact info
 - [ ] Redaction: (yes|no)
  - Allow redaction, editing or structure changes by technical writer staff
 - [ ] Comments: (yes|no)
  - If you're willing to answer comments about your post, set `comments: true`.
  - Make sure to subscribe to your post comments by clicking on the **Subscribe** link at the very bottom of the post _once_ it's published.

@catlook Please review.

### CODE REVIEW

**Comment by catlook** [comment]
build me

**Comment by rackernexus** [comment]
Build 1154 was successful. Staging content [Preview!](https://developer-revs.staging.deconst.org/build-26fd34ae2/). valid for 14 days

**Comment by catlook** [comment]
Maxim's comments:

- There was already a blog post about Cloud Native Security (https://developer.rackspace.com/blog/cloud-native-security-for-aws-comes-to-rackspace/). I don't mind another one, but would like to understand the reasoning behind this 2nd post.

- We recently hosted a joint webinar with AWS on the topic that the new blog post is talking about. It's worth putting a link to it (https://www.brighttalk.com/webcast/17680/387904?utm_source=Rackspace&utm_medium=brighttalk&utm_campaign=387904) as well as to an ebook that talks about this topic (https://s3.amazonaws.com/files.newscred.com/88cab60542c8158bc82f733cce512786).

- Regarding the webinar I mentioned above - it's worth making sure that our messaging in the blog post is aligned to the webinar. For example, both define "cloud native".

- There is a typo in my last name. It should be "Rozin".

- I would avoid using the term CNS and rather use Cloud Native Security. Or at least define it in the beginning of the blog post.

- In the context of CNS, "cloud native" means "cloud vendor native" or "AWS native". The CNSF definition is not too relevant.

- You can include a link to the CNS landing page (https://www.rackspace.com/managed-aws/capabilities/security) or to the more detailed product description (https://developer.rackspace.com/docs/fanatical-support-aws/cloud-native-security/)

- Other than that, it looks great! Thanks for putting this together.

**Comment by catlook** [comment]
build me

**Comment by catlook** [comment]
build me

**Comment by rackernexus** [comment]
Build 1156 was successful. Staging content [Preview!](https://developer-revs.staging.deconst.org/build-efcd6c716/). valid for 14 days

**Pull request merged**
