### PR TITLE
basic text and images

### PR DESCRIPTION
**Pull request by Sterling463**
In a comment on the pull request, include the following information and check off the list.

 - [ ] Mini bio
  - Soft capped to 75 words
 - [ ] Desired date of publishing
  - Make sure this matches the `date` in the front matter
 - [ ] Social media contact info
 - [ ] Redaction: (yes|no)
  - Allow redaction, editing or structure changes by technical writer staff
 - [ ] Comments: (yes|no)
  - If you're willing to answer comments about your post, set `comments: true`.
  - Make sure to subscribe to your post comments by clicking on the **Subscribe** link at the very bottom of the post _once_ it's published.

@catlook Please review.

### CODE REVIEW

**Comment by Sterling463** [comment]
@cyrichardson Would you mind reviewing this PR?

**Comment by cyrichardson** [comment]
On it, @Sterling463.

**Comment by cyrichardson** [comment]
@Sterling463 Please review these changes and see if you agree with them. Thanks!

**Comment by cyrichardson** [comment]
@Sterling463 Note that I did not edit the CTA as it should be boilerplate.

**Comment by Sterling463** [comment]
@catlook obviously no rush but wanted to put this on your radar for next week

**Comment by catlook** [comment]
build error:   Liquid Exception: Couldn't find file '2019-12-6-using-social-studio-to-provide-exceptional-customer-service/Picture1.png' in _posts/2019-12-6-using-social-studio-to-provide-exceptional-customer-service.md/#excerpt

**Comment by rackernexus** [comment]
Build 492 was successful. Staging content [Preview!](https://developer-revs.staging.deconst.org/build-b11a41920/). valid for 14 days

**Comment by rackernexus** [comment]
Build 502 was successful. Staging content [Preview!](https://developer-revs.staging.deconst.org/build-d8fd94496/). valid for 14 days

**Pull request merged**
