### PR TITLE
Paas vnet integration routes

### PR DESCRIPTION
**Pull request by jrudley**
In a comment on the pull request, include the following information and check off the list.

 - [ ] Mini bio
  - Jimmy Rudley is an Azure Architect at Rackspace and an active member of the Azure community. He focuses on solving large and complex architecture and automation problems within Azure.
 - [ ] Desired date of publishing 2020-01-15 00:00
  - Make sure this matches the `date` in the front matter
 - [ ] Social media contact info
 - [ ] Redaction: (yes|no) yes
  - Allow redaction, editing or structure changes by technical writer staff
 - [ ] Comments: (yes|no) yes
  - If you're willing to answer comments about your post, set `comments: true`.
  - Make sure to subscribe to your post comments by clicking on the **Subscribe** link at the very bottom of the post _once_ it's published.

@catlook Please review.

### CODE REVIEW

**Comment by rackernexus** [comment]
Build 631 was successful. Staging content [Preview!](https://developer-revs.staging.deconst.org/build-cc3090354/). valid for 14 days

**Comment by rackernexus** [comment]
Build 632 was successful. Staging content [Preview!](https://developer-revs.staging.deconst.org/build-5099eb696/). valid for 14 days

**Comment by catlook** [comment]
on it!!

**Comment by rackernexus** [comment]
Build 634 was successful. Staging content [Preview!](https://developer-revs.staging.deconst.org/build-5f16e8356/). valid for 14 days

**Comment by cyrichardson** [comment]
On it!

**Comment by rackernexus** [comment]
Build 637 was successful. Staging content [Preview!](https://developer-revs.staging.deconst.org/build-bff21e665/). valid for 14 days

**Comment by rackernexus** [comment]
Build 638 was successful. Staging content [Preview!](https://developer-revs.staging.deconst.org/build-75a9e3913/). valid for 14 days

**Pull request merged**
