### PR TITLE
Classic to lightning

### PR DESCRIPTION
**Pull request by Sterling463**
In a comment on the pull request, include the following information and check off the list.

 - [ ] Mini bio
  - Soft capped to 75 words
 - [ ] Desired date of publishing
  - Make sure this matches the `date` in the front matter
 - [ ] Social media contact info
 - [ ] Redaction: (yes|no)
  - Allow redaction, editing or structure changes by technical writer staff
 - [ ] Comments: (yes|no)
  - If you're willing to answer comments about your post, set `comments: true`.
  - Make sure to subscribe to your post comments by clicking on the **Subscribe** link at the very bottom of the post _once_ it's published.

@cyrichardson Please review at your convenience- Monday am is fine. I am not publishing these blogs until next week.

### CODE REVIEW

**Comment by cyrichardson** [comment]
On it, @Sterling463.

**Comment by rackernexus** [comment]
Build 439 was successful. Staging content [Preview!](https://developer-revs.staging.deconst.org/build-ed26c8f27/). valid for 14 days

**Comment by rackernexus** [comment]
Build 440 was successful. Staging content [Preview!](https://developer-revs.staging.deconst.org/build-472d8656d/). valid for 14 days

**Comment by rackernexus** [comment]
Build 441 was successful. Staging content [Preview!](https://developer-revs.staging.deconst.org/build-a9bc3b083/). valid for 14 days

**Comment by catlook** [comment]
reviewing

**Comment by Sterling463** [comment]
build me

**Comment by WilliamLoy** [comment]
Build me

**Comment by rackernexus** [comment]
Build 446 was successful. Staging content [Preview!](https://developer-revs.staging.deconst.org/build-a9bc3b083/). valid for 14 days

**Comment by rackernexus** [comment]
Build 452 was successful. Staging content [Preview!](https://developer-revs.staging.deconst.org/build-3ee762337/). valid for 14 days

**Comment by cyrichardson** [comment]
@Sterling463 Should you change Process first. to Process First. to be like Technology Second.(r)?

**Comment by Sterling463** [comment]
@cyrichardson will do!

**Comment by Sterling463** [comment]
build me

**Comment by catlook** [comment]
build me

**Comment by rackernexus** [comment]
Build 453 was successful. Staging content [Preview!](https://developer-revs.staging.deconst.org/build-3ee762337/). valid for 14 days

**Comment by rackernexus** [comment]
Build 454 was successful. Staging content [Preview!](https://developer-revs.staging.deconst.org/build-696edbd8f/). valid for 14 days

**Comment by rackernexus** [comment]
Build 460 was successful. Staging content [Preview!](https://developer-revs.staging.deconst.org/build-e6173756f/). valid for 14 days

**Comment by rackernexus** [comment]
Build 461 was successful. Staging content [Preview!](https://developer-revs.staging.deconst.org/build-dfa047b45/). valid for 14 days

**Comment by Sterling463** [comment]
build me

**Comment by Sterling463** [comment]
Build me

**Comment by rackernexus** [comment]
Build 463 was successful. Staging content [Preview!](https://developer-revs.staging.deconst.org/build-a115cfade/). valid for 14 days

**Comment by WilliamLoy** [comment]
Build me

**Comment by rackernexus** [comment]
Build 465 was successful. Staging content [Preview!](https://developer-revs.staging.deconst.org/build-a115cfade/). valid for 14 days

**Pull request merged**
