### PR TITLE
parallel replicat blog

### PR DESCRIPTION
**Pull request by catlook**
In a comment on the pull request, include the following information and check off the list.

 - [ ] Mini bio
  - Soft capped to 75 words
 - [ ] Desired date of publishing
  - Make sure this matches the `date` in the front matter
 - [ ] Social media contact info
 - [ ] Redaction: (yes|no)
  - Allow redaction, editing or structure changes by technical writer staff
 - [ ] Comments: (yes|no)
  - If you're willing to answer comments about your post, set `comments: true`.
  - Make sure to subscribe to your post comments by clicking on the **Subscribe** link at the very bottom of the post _once_ it's published.

@catlook Please review.

### CODE REVIEW

**Comment by rackernexus** [comment]
If you want to double-check your formatting, check [the preview](https://staging.developer.rackspace.com/build-f790e47d7e/).

**Comment by rackernexus** [comment]
:mag_right: [Preview](https://staging.developer.rackspace.com/build-f790e47d7e/)

**Comment by rackernexus** [comment]
HULK [PREVIEW](https://staging.developer.rackspace.com/build-c6daa65d0a/)

**Comment by rackernexus** [comment]
If you want to double-check your formatting, check [the preview](https://staging.developer.rackspace.com/build-7e9aa2c8cf/).

**Comment by rackernexus** [comment]
Your content preview [is now ready](https://staging.developer.rackspace.com/build-96429fa085/). :bow:

**Comment by rackernexus** [comment]
If you want to double-check your formatting, check [the preview](https://staging.developer.rackspace.com/build-4c4a54e6ba/).

**Comment by rackernexus** [comment]
Your content preview [is now ready](https://staging.developer.rackspace.com/build-6263da2eca/). :bow:

**Comment by cyrichardson** [comment]
Suggested changes here: 
[lOracle GoldenGate 12c release 3 - New feature parallel Replicat_cyrEdits.docx](https://github.com/rackerlabs/docs-developer-blog/files/2027358/lOracle.GoldenGate.12c.release.3.-.New.feature.parallel.Replicat_cyrEdits.docx)

**Comment by cyrichardson** [comment]
Suggested changes here: [lOracle GoldenGate 12c release 3 - New feature parallel Replicat_cyrEdits.docx](https://github.com/rackerlabs/docs-developer-blog/files/2027363/lOracle.GoldenGate.12c.release.3.-.New.feature.parallel.Replicat_cyrEdits.docx)

**Comment by rackernexus** [comment]
:mag_right: [Preview](https://staging.developer.rackspace.com/build-6263da2eca/)

**Comment by rackernexus** [comment]
HULK [PREVIEW](https://staging.developer.rackspace.com/build-e404df0010/)

**Comment by rackernexus** [comment]
:eyes: [Preview](https://staging.developer.rackspace.com/build-e404df0010/)

**Comment by rackernexus** [comment]
HULK [PREVIEW](https://staging.developer.rackspace.com/build-9859bad735/)

**Comment by rackernexus** [comment]
:eyes: [Preview](https://staging.developer.rackspace.com/build-093361820e/)

**Pull request merged**
