### PR TITLE
Switched to native escaping of {{ and }} plus other minor fixes

### PR DESCRIPTION
**Pull request by miguelgrinberg**
Here we go one more time. I'm using the native escaping of Jekyll this time, let's hope it works!

### CODE REVIEW

**Comment by rgbkrk** [comment]
Ruh roh, needs a rebase.

**Comment by miguelgrinberg** [comment]
Sorry about that, I missed to include the merge commit of the previous PR in my new branch. Looks like it is a straight merge now.

**Comment by miguelgrinberg** [comment]
@rgbkrk Thanks!

So this looks much better, but the `}}` have an extra quote in them. I used the expression `{{ " }}" }}` for those, which I think is correct, but that's making it render as `" }}` instead of just ` }}`. Any idea why? The same expression works for for the opening brackets.

**Comment by ktbartholomew** [comment]
@miguelgrinberg We're using AngularJS on the page, and it looks like it's trying to parse your curly braces as part of a view-model. This is probably why you've been struggling to get them appear, too. I'll see if we can get Angular to ignore the contents of blog posts so this isn't an issue.

**Comment by miguelgrinberg** [comment]
@ktbartholomew doesn't look like this is a client-side rendering problem, these markers appear fully rendered and with those extra quotes in the page source.

**Comment by ktbartholomew** [comment]
Whether the quotes are accidental or not, it's definitely a BIG client-side problem:

image

**Comment by miguelgrinberg** [comment]
Oh yes, I missed that.

I think I understand what was happening before. The {% raw %}...{% endraw %} tags work fine, but the end result fits the format of the Angular templating, so then Angular goes and erases those client-side. You can see this still happening on this other article: https://developer.rackspace.com/blog/rolling-deployments-with-ansible-and-cloud-load-balancers/.

And now Angular barfs because the server-side rendering creates a template syntax error with those extra quotes. So I agree, the best solution is to disable the Angular templating, and go back to the raw tags.

**Comment by rgbkrk** [comment]
Oh my.

**Pull request merged**
