### PR TITLE
Microsoft Teams post

### PR DESCRIPTION
**Pull request by catlook**
In a comment on the pull request, include the following information and check off the list.

 - [ ] Mini bio
  - Soft capped to 75 words
 - [ ] Desired date of publishing
  - Make sure this matches the `date` in the front matter
 - [ ] Social media contact info
 - [ ] Redaction: (yes|no)
  - Allow redaction, editing or structure changes by technical writer staff
 - [ ] Comments: (yes|no)
  - If you're willing to answer comments about your post, set `comments: true`.
  - Make sure to subscribe to your post comments by clicking on the **Subscribe** link at the very bottom of the post _once_ it's published.

@catlook Please review.

### CODE REVIEW

**Comment by rackernexus** [comment]
Build 349 was successful. Staging content [Preview!](https://developer-revs.staging.deconst.org/build-77962cbdb/). valid for 14 days

**Comment by rackernexus** [comment]
Build 357 was successful. Staging content [Preview!](https://developer-revs.staging.deconst.org/build-139716e97/). valid for 14 days

**Comment by catlook** [comment]
build me

**Comment by catlook** [comment]
build me

**Comment by catlook** [comment]
build me

**Comment by catlook** [comment]
build me

**Comment by rackernexus** [comment]
Build 369 was successful. Staging content [Preview!](https://developer-revs.staging.deconst.org/build-5f149dff5/). valid for 14 days

**Comment by rackernexus** [comment]
Build 370 was successful. Staging content [Preview!](https://developer-revs.staging.deconst.org/build-4f84c8ad0/). valid for 14 days

**Comment by rackernexus** [comment]
Build 373 was successful. Staging content [Preview!](https://developer-revs.staging.deconst.org/build-447d1d26e/). valid for 14 days

**Pull request merged**
