### PR TITLE
initial commit

### PR DESCRIPTION
**Pull request by jrudley**
In a comment on the pull request, include the following information and check off the list.

 - [ ] Mini bio
  - Soft capped to 75 words
 - [ ] Desired date of publishing 7/17/19 or earlier
  - Make sure this matches the `date` in the front matter
 - [ ] Social media contact info
 - [ ] Redaction: (yes|no) yes
  - Allow redaction, editing or structure changes by technical writer staff
 - [ ] Comments: (yes|no) yes
  - If you're willing to answer comments about your post, set `comments: true`.
  - Make sure to subscribe to your post comments by clicking on the **Subscribe** link at the very bottom of the post _once_ it's published.

@catlook Please review.

### CODE REVIEW

**Comment by rackernexus** [comment]
Build 136 was successful. Staging content [Preview!](https://developer-revs.staging.deconst.org/build-6d1cb172f/). valid for 14 days

**Comment by rackernexus** [comment]
Build 137 was successful. Staging content [Preview!](https://developer-revs.staging.deconst.org/build-5556e8c5f/). valid for 14 days

**Comment by catlook** [comment]
back from vacay and on it

**Comment by rackernexus** [comment]
Build 138 was successful. Staging content [Preview!](https://developer-revs.staging.deconst.org/build-14f91679c/). valid for 14 days

**Comment by rackernexus** [comment]
Build 139 was successful. Staging content [Preview!](https://developer-revs.staging.deconst.org/build-acb794d54/). valid for 14 days

**Comment by catlook** [comment]
@jrudley, what do you think?  Good to go?  Or do we need to tweak a bit more?

**Comment by jrudley** [comment]
> @jrudley, what do you think? Good to go? Or do we need to tweak a bit more?

Looks good!

**Pull request merged**
