### PR TITLE
Add edited content and images for new ODI bottlenecks post: INFODEV-2022

### PR DESCRIPTION
**Pull request by RackerKate**
@stephamon  Please review.

### CODE REVIEW

**Comment by rackernexus** [comment]
If you want to double-check your formatting, check [the preview](https://staging.developer.rackspace.com/build-f5086a3a0d/).

**Comment by RackerKate** [comment]
Waiting for text clarification from author.

**Comment by RackerKate** [comment]
@catlook Please review.

**Comment by catlook** [comment]
on it

**Pull request merged**
