### PR TITLE
Add post on OEM Agent: INFODEV-2019

### PR DESCRIPTION
**Pull request by RackerKate**
Still needs SME clarification.

### CODE REVIEW

**Comment by rackernexus** [comment]
Your content preview [is now ready](https://staging.developer.rackspace.com/build-2bf5a4ff9b/). :bow:

**Comment by rackernexus** [comment]
:mag_right: [Preview](https://staging.developer.rackspace.com/build-e51c529f1e/)

**Comment by rackernexus** [comment]
Your content preview [is now ready](https://staging.developer.rackspace.com/build-db35d62722/). :bow:

**Comment by rackernexus** [comment]
:eyes: [Preview](https://staging.developer.rackspace.com/build-f313649a6e/)

**Comment by rackernexus** [comment]
:mag_right: [Preview](https://staging.developer.rackspace.com/build-d13cbca96e/)

**Comment by rackernexus** [comment]
Your content preview [is now ready](https://staging.developer.rackspace.com/build-d13cbca96e/). :bow:

**Comment by rackernexus** [comment]
HULK [PREVIEW](https://staging.developer.rackspace.com/build-3535021079/)

**Comment by RackerKate** [comment]
@cyrichardson For your review.

**Comment by cyrichardson** [comment]
Just a few suggestions here: 
[blog_OEM Agent 12c-Common issues and resolutions_cyrEdits.docx](https://github.com/rackerlabs/docs-developer-blog/files/2241734/blog_OEM.Agent.12c-Common.issues.and.resolutions_cyrEdits.docx)

**Comment by rackernexus** [comment]
HULK [PREVIEW](https://staging.developer.rackspace.com/build-111338fec3/)

**Comment by RackerKate** [comment]
Sent to Smriti & author for their review.

**Comment by rackernexus** [comment]
Your content preview [is now ready](https://staging.developer.rackspace.com/build-111338fec3/). :bow:

**Comment by rackernexus** [comment]
:eyes: [Preview](https://staging.developer.rackspace.com/build-b3d1a6fb8e/)

**Comment by RackerKate** [comment]
@catlook For your review.

**Comment by catlook** [comment]
on it

**Pull request merged**
