### PR TITLE
oswatcher blog

### PR DESCRIPTION
**Pull request by catlook**
In a comment on the pull request, include the following information and check off the list.

 - [ ] Mini bio
  - Soft capped to 75 words
 - [ ] Desired date of publishing
  - Make sure this matches the `date` in the front matter
 - [ ] Social media contact info
 - [ ] Redaction: (yes|no)
  - Allow redaction, editing or structure changes by technical writer staff
 - [ ] Comments: (yes|no)
  - If you're willing to answer comments about your post, set `comments: true`.
  - Make sure to subscribe to your post comments by clicking on the **Subscribe** link at the very bottom of the post _once_ it's published.

@catlook Please review.

### CODE REVIEW

**Comment by rackernexus** [comment]
Build 81 was successful. Staging content [Preview!](https://developer-revs.staging.deconst.org/build-437dcb6cb/). valid for 14 days

**Comment by cyrichardson** [comment]
@catlook Please review editorial changes and see if you agree with them.

**Comment by rackernexus** [comment]
Build 82 was successful. Staging content [Preview!](https://developer-revs.staging.deconst.org/build-7dc855e19/). valid for 14 days

**Comment by rackernexus** [comment]
Build 83 was successful. Staging content [Preview!](https://developer-revs.staging.deconst.org/build-e2a56c5dc/). valid for 14 days

**Comment by rackernexus** [comment]
Build 84 was successful. Staging content [Preview!](https://developer-revs.staging.deconst.org/build-b3f278dc4/). valid for 14 days

**Pull request merged**
